.eslintrc.json, components/Layout.tsx, package.json, pages/_app.tsx, tools/hooks/useLocalStorage.ts, tools/hooks/useSessionStorage.ts, tsconfig.json, yarn.lock
- Install Unstated Next
- Add `useLocalStorage` and `useSessionStorage` hooks
- Small linting/TypeScript changes
=> [Feature] Setup state management

lib/graphql/apollo.ts, prisma/index.ts, prisma/schema.prisma, prisma/schema.sql, tsconfig.json
=> [Feature] Initialized schema + setup prisma

apollo.config.js, lib/db/errors.ts, lib/employees/errors.ts, lib/employees/resolvers.ts, lib/employees/schema.graphql, lib/graphql/apollo.ts, lib/graphql/context.ts, lib/graphql/resolvers.ts, lib/graphql/schema.graphql, lib/graphql/types.ts, lib/meta/resolvers.ts, lib/scripts/generate-graphql-types.js
- Created Employee GraphQL queries and mutations (create)
- Added enums to top-level GraphQL schema
- Isolated GraphQL `context` into separate file
- Small fix to `generate-graphql-types` script (was breaking if `types.ts` did not exist)
- Removed unused configuration in `apollo.config.js`
=> [Feature] Employee GraphQL queries

.github/workflows/ci.yml, .github/workflows/pull_request_template.md, package.json
- Added a CI workflow that builds code + runs prettier and lint checks
-  Added linting and prettier scripts to `package.json`
- Added PR template (when you add a pull request template to your repository, you will automatically see the template's contents in the pull request body)
=> [Feature] Set up CI workflow + add linting and prettier scripts

README.md, package.json, prisma/seed.ts, yarn.lock
[Seed database with sample data](https://www.notion.so/uwblueprintexecs/Seed-database-with-sample-data-5619a2ae9c8f4f3e8a718b52beff5125)
* The employees table in your dev db can now be populated with sample data by running the command `npx prisma db seed --preview-feature`
* Separate function to seed dev db and prod db
* Followed Prisma's [seed database guide](https://www.prisma.io/docs/guides/database/seed-database)
* See my comments below for things I thought I'd clarify (https://github.com/uwblueprint/richmond-centre-for-disability/pull/13#discussion_r654075064, https://github.com/uwblueprint/richmond-centre-for-disability/pull/13#discussion_r654075774)
=> [Feature] Set up db seeding

lib/graphql/resolvers.ts, lib/graphql/schema.graphql, lib/permits/errors.ts, lib/permits/resolvers.ts, lib/permits/schema.graphql, prisma/schema.prisma
[Set up GQL queries for Permits](https://www.notion.so/uwblueprintexecs/Set-up-GQL-queries-for-Permits-a163b57945524a97bb143d08c1bdd41f)
- Added GraphQL queries `permits` and mutations `createPermit`
- Generated Typescript types
- BLOCKED: referencing application and applicant from `applicationId` and `applicantId`
=> [Feature] GraphQL queries for permits model

components/internal/Table.tsx, package.json, pages/admin/index.tsx, tools/theme/colors.ts, tools/theme/components/table.ts, tools/theme/index.ts, yarn.lock
[RCD-facing Request Table skeleton](https://www.notion.so/uwblueprintexecs/RCD-facing-Request-Table-skeleton-f769b98c16494ea8a3dfa3a6539de9bf)
* Created a custom table component with styling and props `columns` + `data` using react-table (_Table.tsx_)
* Created a request table (using custom table component) in admin landing page (_admin/index.tsx_) with sample data
* Table component can't currently sort, filter, search, or paginate
* Request table functionalities not fully implemented and is not connected to database
Screenshot of Request table in admin landing page:
=> RCD-facing Request Table skeleton

components/applicant/Layout.tsx, components/internal/Layout.tsx, pages/admin/login.tsx
N/A
* Design foundation for internal-facing pages do not have a max width (due to tables having many columns) - removed this property
* Made some small fixes to the configuration in the internal `Layout` component
* Fixed the width of the login "card" on the internal login page to 640px (design decision
* This change should go in before the upcoming internal frontend features are implemented
=> [Improvement] Remove max width from internal layout component

lib/applicants/field-resolvers.ts, lib/applicants/resolvers.ts, lib/applicants/schema.graphql, lib/graphql/resolvers.ts, lib/graphql/schema.graphql, lib/graphql/types.ts, prisma/schema.prisma
[Create applicant GQL API](https://www.notion.so/uwblueprintexecs/Create-applicant-GQL-API-72de66c7d59b4702a0406ea6eef23907)
[Create medicalHistory GQL API](https://www.notion.so/uwblueprintexecs/Create-medicalHistory-GQL-API-a8dad0ecadff4e4bbbf0edb436530fd9)
* Created the applicant and medicalHistory GQL API. Added an applicant query to @lib/graphql/schema.graphql and created the function in @lib/applicants/resolvers.ts following closely on previous resolver calls. Added another nested resolver to applicant for medicalHistory and created a medicalHistory type in lib/applicants/schema.graphql. Added the medicalHistory function to field-resolvers.ts for applicants. 
*
=> [Feature] Create applicant and medicalHistory GQL APIs

components/internal/Layout.tsx, components/internal/PermitHolderInfoCard.tsx, components/internal/RequestStatusBadge.tsx, components/requests/ApproveModal.tsx, components/requests/DoctorInformationCard.tsx, components/requests/PaymentInformationCard.tsx, components/requests/PersonalInformationCard.tsx, components/requests/ProcessingTaskStep.tsx, components/requests/ProcessingTasksCard.tsx, components/requests/ReasonForReplacementCard.tsx, components/requests/RejectModal.tsx, components/requests/RequestHeader.tsx, components/requests/modals/ApproveRequestModal.tsx, components/requests/modals/AssignNumberModal.tsx, components/requests/modals/CompleteRequestModal.tsx, components/requests/modals/EditDoctorInformationModal.tsx, components/requests/modals/EditPaymentDetailsModal.tsx, components/requests/modals/EditReasonForReplacementModal.tsx, components/requests/modals/RejectRequestModal.tsx, lib/utils/format.ts, pages/admin/request/[requestId].tsx, tools/theme/colors.ts, tools/theme/components/badge.ts
[Add request page frontend](https://www.notion.so/uwblueprintexecs/ac7b1f636a214a0cbf45f6b76f899b54?v=5414ee5fc5974f149921e192d6eb29b8&p=b1f5d9138e0e4ca0b91ce0024a34bd11)
[Add request page header (also frontend)](https://www.notion.so/uwblueprintexecs/ac7b1f636a214a0cbf45f6b76f899b54?v=5414ee5fc5974f149921e192d6eb29b8&p=1520cec1670d4033b435f1c4ab59cec6)
* Adds the flow here for an individual request to be processed by an admin: https://www.figma.com/file/GjxN42wF0Qr7tbtaBV4Xoj/RCD-%2F-RCD-Experience?node-id=4%3A3
=> [Feature] Add complete progress renewal/replacement request page

lib/graphql/schema.graphql, lib/graphql/types.ts, package.json, prisma/schema.prisma, prisma/schema.sql, prisma/seed.ts, yarn.lock
[Ticket](https://www.notion.so/uwblueprintexecs/Misc-Database-changes-df7c8a3015df4adfa716edd3ae171a12)
* Please see ticket for details regarding main tasks completed in this PR
* Updated seeding script with replacement and application processing records
* Updated main GraphQL schema to include new enums - these are now available by importing `@lib/types`!
* Small fixes to existing SQL schema (eg. adding `UNIQUE` constraint to foreign key for one-to-one relationship)
* Updated `prisma` and `@prisma/client`
* This PR unblocks various upcoming API hookup tasks - please review carefully to ensure that no important fields were missed!
=> [Improvement] Misc. DB Changes for MVP API hookups

components/internal/Table.tsx, package.json, pages/admin/permit-holders.tsx, tools/theme/colors.ts, yarn.lock
[Permit Holders Table Page](https://www.notion.so/uwblueprintexecs/Permit-Holders-Table-Page-52ce53d70edb417cbdb3352f0ae265ce)
- create table in permit holders page
- filter, search and sorting
- react-day-picker for calendar dropdown and react-helmet for styling calendar
- added react helmet based on the[ date picker docs](http://react-day-picker.js.org/examples/selected-range#:~:text=%3CHelmet%3E%0A%20%20%20%20%20%20%20%20%20%20%3Cstyle%3E%7B%60%0A%20%20.Selectable,important%3B%0A%20%20%7D%0A%60%7D%3C/style%3E%0A%20%20%20%20%20%20%20%20%3C/Helmet%3E)
=> [Feature] Create permit holders table page

components/internal/Table.tsx, pages/admin/index.tsx
[Request Table page](https://www.notion.so/uwblueprintexecs/Requests-Table-page-e6290e4f165e464283ec249fb8b062f9)
* Front end for Request Table Page
* populating table with real data and applying filters will be done as part of the related API hookup ticket
=> [Feature] Build Requests Table Page

components/internal/modals/EditPermitHolderInformationModal.tsx, components/internal/modals/EditUserInformationModal.tsx, components/requests/modals/EditDoctorInformationModal.tsx, components/requests/modals/EditPaymentDetailsModal.tsx, components/requests/modals/EditReasonForReplacementModal.tsx, pages/index.tsx
[Edit Permit Holder Modals](https://www.notion.so/uwblueprintexecs/Edit-Permit-Holder-Modals-1f99f1b1d48f4fc0b29234a8cb238a26)
* Built `EditUserInformationModal` and `EditPermitHolderInformationModal`. Implementation closely follows how the previous modals (`EditPaymentDetailsModal`, `EditDoctorInformationModal`, `EditReasonForReplacementModal`) were built
* Similar to the other the modals, error states + handling will be addressed later (probably post-mvp)
=> [Feature] Build Edit Permit Holder modals

lib/applicants/resolvers.ts, lib/applications/resolvers.ts, prisma/index.ts
[Fix name searching in Request table page](https://www.notion.so/uwblueprintexecs/Fix-name-searching-in-Request-table-page-8a19c602bf7449d2aa1bc6da2d84d70f)
* Added extra logic in resolvers to handle the different cases
* Added some bulk in the resolver but it solves the issues, is there a simpler way to do this?
=> [Fix] Fix name searching in Request table & Permit-Holders table

prisma/dev-seed-utils/employees.ts
[Ticket](https://www.notion.so/uwblueprintexecs/Update-staging-employee-data-de12006db9ff468d8dda816a3ab681e1)
* Add new employee accounts to seeding for Carelynn, Andy, Amanda and Anish
=> [Improvement] Update employee seeding data

components/permit-holders/AppHistoryCard.tsx, components/permit-holders/AttachedFilesCard.tsx, components/permit-holders/MedicalHistoryCard.tsx, components/permit-holders/PersonalInformationCard.tsx, components/permit-holders/modals/EditUserInformationModal.tsx, components/permit-holders/modals/MedicalHistoryModal.tsx, components/requests/modals/EditReasonForReplacementModal.tsx, lib/utils/format.ts, pages/admin/index.tsx, pages/admin/permit-holders.tsx, pages/verify-identity.tsx
[Permit Holders table showing incorrect date of birth](https://www.notion.so/uwblueprintexecs/Permit-Holders-table-showing-incorrect-date-of-birth-0e58daefb7da4e28a2470f27cd6fab41)
Ticket co-assignee @EmilioMena 
* Dates were being converted to a different time zone when displayed which set the date back by one day ( e.g date of birth should be September 11th -> was shown as September 10th because of time zone conversion). To address this a util function `formatDate` was created that explicitly set the time zone to UTC.
* I swept through the codebase and refactored how we showed dates to use the `formatDate` function instead which makes most of the dates in the app have a MM/DD/YYYY format (1st pic)
* The dates on the Date received column in the requests table were changed from a …
=> [Fix] Fix incorrect dates displayed

pages/admin/admin-management.tsx, public/assets/three-dots.svg, tools/theme/colors.ts
[Build Admin Management Table Frontend](https://www.notion.so/uwblueprintexecs/ac7b1f636a214a0cbf45f6b76f899b54?v=5414ee5fc5974f149921e192d6eb29b8&p=0f020b55861d4ae2821ac075291f9c36)
* Admin Management Table Frontend
* Still need to figure out dimming text on select.
=> [Feature] Create Admin Management Table Frontend

lib/employees/schema.ts, lib/graphql/types.ts, prisma/schema.prisma, prisma/schema.sql
Add an active column to Employee DB model (https://www.notion.so/uwblueprintexecs/Add-active-column-to-Employee-DB-model-5c64477da9314801bd34a7321b032c38)
* to support soft deletion of employees, an active column must be added to the employee schema
*
=> [Improvement] Add active column to employee db

lib/employees/resolvers.ts, lib/employees/schema.ts, lib/graphql/schema.ts, lib/graphql/types.ts
[Add sorting to employees API](https://www.notion.so/uwblueprintexecs/Add-sorting-to-employees-API-bfedaac4fe1a4f85abcc7adb2e438936)
* Created EmployeesFilter and updated employees resolver to allow for sorting
* See comments
* Tested on GraphQL playground
=> [Feature] Add sorting to employees API

components/admin-management/AdminModal.tsx, pages/admin/admin-management.tsx
["Add new user" and "Edit user" Modal Frontend](https://www.notion.so/uwblueprintexecs/Add-New-user-and-Edit-user-modal-frontend-5e7af2ee4311406eb4e57caf9727fc08)
- Created AdminModal component under components/admin-management/modals
- Created "Add new user" and "Edit user" modals using AdminModal component 
- Linked "Add new user" modal to "Add an RCD User" button
- Linked "Edit user" modal to table "Actions" column, "Edit user" dropdown, the modal will already be populated with fields from the table data
- Clicking "Cancel" or in the modal overlay will close the modal
- Clicking "Save" will save form field data and closes the modal
* "Edit user" modal will not have the first name and last name pre-populated because our current hardcoded data does not separate the name into first and …
=> [Feature] Build Add new user and Edit user Modal Frontend

pages/admin/index.tsx, pages/admin/permit-holders.tsx
[Truncate Names on Requests & Permit Holder tables](https://www.notion.so/uwblueprintexecs/Truncate-Names-on-Requests-Permit-Holder-tables-eae393474f2f4980a380f69f963c9abc)
* Add chakra `Tooltip` component
* add extra css for overflow and ellipsis (`white-space`, `overflow`, `text-overflow`, `max-width`)
* I'm not the best with css so if any of you css wizards know of a better way to do this lmk!
=> [Fix] Truncate Names on Requests & Permit Holder tables

lib/scripts/oneoff/populate-db-10-01-2021.js
[Ticket](https://www.notion.so/uwblueprintexecs/Seed-staging-database-with-RCD-sample-data-with-pending-applications-63682662038648da9ccc965ed88fca94)
Diffs with previous seeding script:
* Removed all completed application processing data so that the application processing defaults to pending
* Took sample permit data and adjusted expiry date to be 3 years earlier so that every applicant has an existing expired APP (`mostRecentPermit`) and as such, new applications will be valid renewals
* This ticket was created ad-hoc following discussion with PM regarding use case of seeding dummy data, which only needs to happen for user interviews. Furthermore, we can use the sample data that RCD provided to us for a more realistic demo. Thus, a new DB population script derived from …
=> [Misc] Seed staging DB with sample data with pending applications

lib/employees/resolvers.ts, lib/employees/schema.ts, lib/graphql/schema.ts, lib/graphql/types.ts, pages/admin/admin-management.tsx, tools/pages/admin/admin-management/get-employees.ts, tools/pages/admin/admin-management/types.ts
[Admin Management Table API Hookup](https://www.notion.so/uwblueprintexecs/Admin-Management-Table-API-Hookup-Get-employees-bf06d2f8e6374afb85a43e970701f09c)
* utilized useQuery to fetch employees
* made gql query for employees
* added active flag to prisma call
* added sorting to employee resolver
Current frontend design: 
Sorting names:
* column styling not accurate to figma design but this might not be addressed in this PR
=> [Feature] Admin management table hookup

lib/employees/errors.ts, lib/employees/resolvers.ts, lib/employees/schema.ts, lib/graphql/resolvers.ts, lib/graphql/schema.ts, lib/graphql/types.ts
[Delete employee endpoint](calendar.google.com/calendar/u/0/r/week?eid=MnZodjRwZmVjbmJtZWdsM2tmbDhibXJkdTMgYW5pc2hhZ2dhcndhbEB1d2JsdWVwcmludC5vcmc&ctok=YW5pc2hhZ2dhcndhbEB1d2JsdWVwcmludC5vcmc&pli=1)
* Added Resolver for checking condition of employee with given ID in database
* Updated active state if correct qualifications, otherwise threw error.
* Conditions include:
1. Employee does not exist in DB -> EmployeeNotFoundError
2. Employee already deleted from DB -> EmployeeAlreadyDeletedError
* Case: Deleting Non-existant User
* Case: Normal Deletion
* Case: Double Deletion
P.S. : I noticed that it says ID undefined in message, but that has been fixed due to a type. :D
i.e.
=> [Feature] Added (Soft) Delete Employee Endpoint.

components/applicant/Layout.tsx, components/internal/Layout.tsx, components/internal/Table.tsx, pages/admin/admin-management.tsx, pages/admin/index.tsx, pages/admin/permit-holders.tsx
Combined three colour change tickets into one:
1) [Change Table Background Colour to white (#FFFFFF)](https://www.notion.so/uwblueprintexecs/Change-Table-Background-Colour-to-white-FFFFFF-9d3534e3d1bc4196a4f96b17c826ca31)
2) [Change Page Background Color to different Background/Grey (#F8F8F9)](https://www.notion.so/uwblueprintexecs/Change-Page-Background-Color-to-different-Background-Grey-F8F8F9-22d0f5bf3c624f9fb946f2fdc769af1b)
3) [Change Table row interaction colour, on:hover should be #F4F6FC (Background/Interactive)](https://www.notion.so/uwblueprintexecs/Change-Table-row-interaction-colour-on-hover-should-be-F4F6FC-Background-Interactive-33cf5bcef7b548b7a36985c8f01cc053)
1) Changed background colour of request table to white in index.tsx
2) Changed background colour of pages to grey …
=> [Fix] Change Table Background, Row Interaction, and Page Background Colour

lib/employees/resolvers.ts, lib/employees/schema.ts, lib/graphql/types.ts, pages/admin/admin-management.tsx, tools/pages/admin/admin-management/get-employees.ts
[Admin Management Table API + Hookup - Pagination](https://www.notion.so/uwblueprintexecs/Admin-Management-Table-API-Hookup-Pagination-fe38ad0c198f427786757a0a35d25e92)
API:
* Added limit and offset parameters to the `EmployeesFilter` input type in `lib/employees/schema.ts`
* Added totalCount field to the `QueryEmployeesResult` type in `lib/employees/schema.ts`
* Modified the employees resolver to pass these parameter values to the Prisma query
* Modified the employees resolver to also query for the total number of results
Frontend:
* Modified the`useQuery` hook in `pages/admin/admin-management.tsx` to retrieve paginated results
* Replaced the props in the `Pagination` component in `pages/admin/admin-management.tsx` with a newly created `PAGE_SIZE` variable and the offset state variable …
=> [Feature] Admin Management Table Pagination API + Hookup

lib/applicants/resolvers.ts, lib/applications/errors.ts, lib/applications/resolvers.ts, lib/applications/schema.ts, lib/graphql/resolvers.ts, lib/graphql/schema.ts, lib/graphql/types.ts
[Create New Replacement Request Endpoint](https://www.notion.so/uwblueprintexecs/ac7b1f636a214a0cbf45f6b76f899b54?v=5414ee5fc5974f149921e192d6eb29b8&p=17c56ec2080a464b82066f24315c982e)
* Added Resolver and Schema changes for new endpoint
* Tested in GQL Playground:
=> [Improvement] Create New Replacement Request Endpoint

next.config.js, package.json, tsconfig.json, yarn.lock
[Ticket](https://www.notion.so/uwblueprintexecs/Upgrade-to-Next-js-12-ab4514a67dad4786af9953c6f726ff04)
* Upgraded React to latest and Next.js to version 12
* Removed `target` property from `next.config.js` as it is now deprecated
* Regression testing in progress
=> [Improvement] Upgrade Next.js to version 12

components/admin/permit-holders/DoctorInformationCard.tsx, components/admin/requests/forms/DoctorInformationForm.tsx, components/admin/requests/modals/EditDoctorInformationModal.tsx, pages/admin/request/create-renewal.tsx, pages/requests/create-renewal.tsx, tools/components/admin/requests/forms/doctor-information-form.ts, tools/components/admin/requests/forms/types.ts
[New Renewal Request Page Frontend](https://www.notion.so/uwblueprintexecs/New-Renewal-Request-Page-Frontend-a0fab1a71d774267841c26822cdfbcdb)
* Created new `create-renewal` page under pages/requests/create-renewal.tsx
* Added temporary text input field to act as the Typeahead component
* Added `PermitHolderInformationForm`, `DoctorInformationForm`, `AdditionalQuestionsForm`, and `PaymentDetailsForm` components with state variables and state setters
* Built footer component, sticks to bottom of page when scrolling
* No integrated Typeahead component yet
* No functionality with buttons, user ID links, etc.
=> [Feature] New Renewal Request Page Frontend

components/admin/requests/modals/CancelCreateRequestModal.tsx, pages/admin/request/create-renewal.tsx, pages/admin/request/create-replacement.tsx
[Add Cancel Request Modals for New Replacement and Renewal Requests](https://www.notion.so/uwblueprintexecs/Add-Cancel-Request-Modals-for-New-Replacement-and-Renewal-Requests-aa26111a9ffe45e4b3832bc8e7ec76ab)
* Created modal for when users click "cancel" on the bottom of create renewal and create replacement forms
* Modal closes when user selects "close" 
* Modal redirects user to /admin when user selects "cancel"
*
=> [Feature] Add Cancel Request Modals for New Replacement and Renewal Requests

components/admin/requests/forms/new-applications/GuardianInformationForm.tsx, components/admin/requests/forms/new-applications/PhysicianAssessmentForm.tsx, lib/graphql/types.ts, pages/admin/index.tsx, pages/admin/request/create-renewal.tsx, tools/components/admin/requests/forms/types.ts
[New APP Requests Page - PhysicianAssessment and GuardianInformation forms frontend](https://www.notion.so/uwblueprintexecs/New-APP-Requests-Page-PhysicianAssessment-and-GuardianInformation-forms-frontend-c3d4be78ef7245a0a0d2368e7e61a842)
* Created 2 new form components in `components/requests/forms/new-applications/PhysicianAssessmentForm.tsx` and `components/requests/forms/new-applications/GuardianInformationForm.tsx`
*
=> [Feature] PhysicianAssessment and GuardianInformation new app forms

components/admin/reports/GenerateReportModal.tsx, lib/applications/resolvers.ts, lib/applications/schema.ts, lib/graphql/resolvers.ts, lib/graphql/schema.ts, lib/graphql/types.ts, tools/pages/admin/requests/queries.ts
Co-authored with @jennifertsai 
[Reports - Hookup Requests Report Endpoint to frontend](https://www.notion.so/uwblueprintexecs/Reports-Hookup-Requests-Report-Endpoint-to-frontend-4b14380cb15043e98e22875ed8eae6ac)
* Added state for checkboxes
* Hooked modal up to endpoint
https://user-images.githubusercontent.com/51224641/145312664-323adbb6-6ff7-4435-af09-8e3a04fcdc0f.mov
*
=> [Feature] Hookup Requests Report Endpoint to frontend

components/admin/Layout.tsx, components/admin/permit-holders/MedicalHistoryCard.tsx, components/admin/permit-holders/PermitHolderHeader.tsx, components/admin/reports/GenerateReportModal.tsx, pages/admin/admin-management.tsx, pages/admin/index.tsx, pages/admin/login.tsx, pages/admin/permit-holder/[id].tsx, pages/admin/permit-holders.tsx, pages/admin/request/create-renewal.tsx, pages/admin/request/create-replacement.tsx, pages/index.tsx, pages/renew.tsx, pages/verify-identity.tsx
1. [Make toasts closable](https://www.notion.so/uwblueprintexecs/Make-toasts-closable-e9dfd80199bc480fb40b7ca90e92a378)
2. [Fix Typography of Name Column in Requests and Permit Holders Tables](https://www.notion.so/uwblueprintexecs/Fix-Typography-of-Name-Column-in-Requests-and-Permit-Holders-Tables-edd836dd25ec41d49106c05b8750a7a7)
3. [Fix copy for Log out button in Navbar](https://www.notion.so/uwblueprintexecs/Fix-copy-for-Log-out-button-in-Navbar-9e81c6e6f2c94319aa32c5819fe59547)
4. [Remove underline in "View details" link in Medical History Card](https://www.notion.so/uwblueprintexecs/Remove-underline-in-View-details-link-in-Medical-History-Card-1e3110f6150043aaa45b8ca9986ad43a)
5. [Adjust Header and subheader margin on permit holder information …
=> [Fix] Various bug fixes

lib/scripts/oneoff/populate-db-10-01-2021.js, prisma/dev-seed-utils/employees.ts, prisma/schema.prisma, prisma/schema.sql, yarn.lock
N/A
* Repopulate staging DB following recent DB changes (eg. `patient_eligibility` column)
* Temporary fix for staging DB, more changes to `populate-db` files to come following more DB schema changes
=> [Hotfix] Fix DB population script for seeding staging

components/admin/permit-holders/permit-holder-information/EditModal.tsx, components/admin/requests/additional-questions/Form.tsx, components/admin/requests/doctor-information/Form.tsx, components/admin/requests/guardian-information/Form.tsx, components/admin/requests/payment-information/Form.tsx, components/admin/requests/permit-holder-information/Card.tsx, components/admin/requests/permit-holder-information/EditModal.tsx, components/admin/requests/permit-holder-information/Form.tsx, components/admin/requests/physician-assessment/Form.tsx, components/admin/requests/reason-for-replacement/Form.tsx, lib/applications/resolvers.ts, lib/applications/schema.ts, lib/graphql/resolvers.ts, lib/graphql/schema.ts, lib/graphql/types.ts, lib/utils/format.ts, pages/admin/index.tsx, pages/admin/request/create-new.tsx, pages/admin/request/create-renewal.tsx, pages/admin/request/create-replacement.tsx, tools/admin/requests/additional-questions.ts, tools/admin/requests/create-new.ts, tools/admin/requests/guardian-information.ts, tools/admin/requests/payment-information.ts, tools/admin/requests/permit-holder-information.ts, tools/admin/requests/physician-assessment.ts
**WIP, more testing needed**
[Ticket](https://www.notion.so/uwblueprintexecs/Create-a-New-Request-New-APP-Request-Frontend-e75983c66a904857a6d8f957d3720199)
* Built Create New APP Request frontend
* With state management, except file selector (TODO)
* Right now, there are a lot of repeated elements in the create new, renewal, and replacement application flows. We should take some time next term to reduce redundancy and make the code easier to maintain
* Loading states are WIP, coordinate with https://github.com/uwblueprint/richmond-centre-for-disability/pull/117 to reduce redundancy of loading UIs - used a placeholder spinner for now
* There is currently an issue with button heights, WIP
=> [Feature] Build Create New APP Request frontend + API hookup

lib/graphql/resolvers.ts, lib/graphql/schema.ts, lib/graphql/type-defs.ts, lib/graphql/types.ts, lib/reports/resolvers.ts, lib/reports/schema.ts, lib/utils/format.ts
[Build Accountant Reports Generation API](https://www.notion.so/uwblueprintexecs/Build-Accountant-Reports-Generation-API-698a110be5a045989838e72cf5792701)
[Desired CSV](https://docs.google.com/document/d/1zeNH_U_-bN5NsABBIq_0WMFrAMy4ED-ffbCUBNJVWcY/edit#heading=h.ydup5da146j8) - given by design
Normal Query: 
Generated CSV: 
- Second opinion: _is there a more optimal way of generating the leftmost column headers?_
- To-do: modify API to return link from AWS
- Note: file.csv is stored in temp for now
=> [Feature] Accounting Report Generation API

pages/admin/reports.tsx, tools/admin/permit-holders/graphql/generate-report.ts
[Generate Accountant Report API Hookup](https://www.notion.so/uwblueprintexecs/Generate-Accountant-Report-API-hookup-2586ec22d49c4982a2050440e7a32ae4)
* Recycled previous permit holders CSV generation functions 
* Added query to [generate-report.ts](https://github.com/uwblueprint/richmond-centre-for-disability/pull/140/files#diff-c175b88338731d848ac819c8b804a0e546397529b94c95d1a8e3533f7794b6e7) to import in front-end
* Blocked By #136 (Wait until merge to merge)
* Need clarification on design of loading state (where to appear, and when)
=> [Improvement] Generate Accountant Report API Hookup

pages/api/payment-received.ts
[Add donation data to Shopify payment webhook](https://www.notion.so/uwblueprintexecs/Add-donation-data-to-Shopify-payment-webhook-1349af02abda47988b4e14ef5d1451ef)
_Updated application with donation after webhook request_
* Get donation from request, convert to Prisma Decimal type, save to DB
* Add some comments I thought were missing
* Shopify considers a donation to be a line item. So we actually need to check which index in the `line_items` array the Permit line item is to grab the application ID from its custom attributes.
* I assumed that there will ever only be 1 or 2 line items in a checkout
=> [Fix] Add donation data to Shopify payment webhook

lib/utils/upload-to-s3.ts, pages/admin/request/create-new.tsx, pages/api/s3-upload.ts, tools/hooks/useS3UploadEdit.ts
[Restrict view access for S3 documents](https://www.notion.so/uwblueprintexecs/Restrict-view-access-for-S3-documents-b8fbc6f6eebc476b997f77b0673ddd84)
This PR makes the necessary changes to allow s3 files to be private while allowing access through pre-signed, temporary urls generated by our application. AWS changes documented in the ticket
Changes
- Create our own uploadToS3 function modified from the [next-s3-upload hook](https://github.com/ryanto/next-s3-upload/blob/master/packages/next-s3-upload/src/hooks/use-s3-upload.tsx)
- main modification is changing the [ACL field](https://github.com/ryanto/next-s3-upload/blob/master/packages/next-s3-upload/src/hooks/use-s3-upload.tsx#L67) to be private
- remove the hook and state features from it since we don't really need them
- Wrap the …
=> [Feature] Make S3 Upload Links Private

components/form/TextField.tsx, lib/auth/validation.ts, package.json, pages/admin/login.tsx, pages/api/auth/[...nextauth].ts, yarn.lock
[Set up form validation](https://www.notion.so/uwblueprintexecs/Set-up-form-validation-7a2ace2dcc97465bacd2a1090d69bc2d)
* Installed Formik and Yup
* Added backend and frontend validation for the login page
Backend validation details:
* Added a Yup validation schema for login
* Throw one of the following error messages if login fails
* `Invalid email input` if email does not match validation schema
* `This email has not been registered by the admin.` if user does not exist
* `Internal server error` for all other errors
Frontend validation details:
* Created a reusable form text field component that integrates with Formik error messages and field labels
* Refactored previous login form to use Formik components
https://user-images.githubusercontent.com/35577524/157576023-268faf5c-0c3c-4e2b-8 …
=> [Misc] Form validation setup

components/admin/requests/doctor-information/Card.tsx, components/admin/requests/payment-information/Card.tsx, components/admin/requests/permit-holder-information/Card.tsx, components/admin/requests/processing/ReviewInformationModal.tsx, components/admin/requests/processing/TasksCard.tsx, components/admin/requests/reason-for-replacement/Card.tsx
[Review Information Modal](https://www.notion.so/uwblueprintexecs/ac7b1f636a214a0cbf45f6b76f899b54?v=5414ee5fc5974f149921e192d6eb29b8&p=10949502df4a426cb907b19524d88a0f)
* Added Review Information Modal and edited the cards to remove editing
* Requires hookup with task management
* Requires Hookup - should remove location of state and add string request Type depending on where task management occurs
* Follow up: create additional information modal
=> [Feature] Build Review Information Modal

components/admin/requests/reason-for-replacement/Card.tsx, components/admin/requests/reason-for-replacement/EditModal.tsx, components/admin/requests/reason-for-replacement/Form.tsx, components/form/DateField.tsx, lib/applicants/validation.ts, lib/applications/validation.ts, pages/admin/request/create-replacement.tsx, tools/admin/requests/create-replacement.ts
[Reason For Replacement Form Validation](https://www.notion.so/uwblueprintexecs/Reason-For-Replacement-Form-Validation-2773eb887500494a97fb0cf86c8906d5)
* 
* Merge #165 before this one
=> [Feature] Reason For Replacement Form Validation

components/admin/requests/additional-questions/Form.tsx, components/form/RadioGroupField.tsx, lib/applicants/validation.ts, lib/applications/validation.ts, pages/admin/request/create-new.tsx, pages/admin/request/create-renewal.tsx
[Additional Information Form Validation](https://www.notion.so/uwblueprintexecs/Additional-Information-Form-Validation-b8e073c911e048939b0418abdc3ebfa9)
TODOs:
*
=> [Feature] Additional Information Form Validation

components/admin/permit-holders/reports/GenerateModal.tsx, lib/graphql/types.ts, lib/reports/resolvers.ts, lib/reports/schema.ts, tools/admin/permit-holders/graphql/generate-report.ts
[Upload permit holders report to S3](https://www.notion.so/uwblueprintexecs/Upload-permit-holders-report-to-S3-aca3627fad01485dba1e2a7db97ea395)
* Following https://github.com/uwblueprint/richmond-centre-for-disability/pull/173 and https://github.com/uwblueprint/richmond-centre-for-disability/pull/176
* 
[permit-holders-report-2-20220427-191419.csv](https://github.com/uwblueprint/richmond-centre-for-disability/files/8578376/permit-holders-report-2-20220427-191419.csv)
=> [Improvement] Upload Permit Holders report to S3

lib/graphql/types.ts, lib/reports/resolvers.ts, lib/reports/schema.ts, pages/admin/reports.tsx, tools/admin/permit-holders/graphql/generate-report.ts
[Upload accounting report to S3](https://www.notion.so/uwblueprintexecs/Upload-accounting-report-to-S3-c3110beb9bc646b0823d7cf3c414a0af)
Closely follows https://github.com/uwblueprint/richmond-centre-for-disability/pull/173
https://user-images.githubusercontent.com/51224641/165640117-4dfcf532-31f3-4467-9e58-10129f7215a8.mov
[accounting-report-3-20220427-181414.csv](https://github.com/uwblueprint/richmond-centre-for-disability/files/8578113/accounting-report-3-20220427-181414.csv)
=> [Feature] Upload accounting report to S3

components/admin/requests/Header.tsx
[Disable approving already-rejected requests](https://www.notion.so/uwblueprintexecs/Disable-approving-already-rejected-requests-0e2f32192ddd403a8330036841212594)
* Removed rejected application status from conditional block 
*
=> [Fix] Remove more actions dropdown for rejected request

pages/renew.tsx
[Loading States Applicant Flow](https://www.notion.so/uwblueprintexecs/Loading-States-Applicant-Flow-0ced24a0b548458f827728d67915852f)
* loading states were basically already there, just needed one simple change
*
=> Add loading states to applicant flow

components/admin/permit-holders/Header.tsx, components/admin/permit-holders/table/ConfirmSetActiveModal.tsx, components/admin/permit-holders/table/ConfirmSetInactiveModal.tsx, pages/admin/permit-holders.tsx, tools/admin/permit-holders/permit-holders-table.ts
[Hookup set as active modal to setApplicantAsActive endpoint](https://www.notion.so/uwblueprintexecs/Hookup-set-as-active-modal-to-setApplicantAsActive-endpoint-7580903d96fb495fa0c5d80003cb54fa)
* closely followed #175 
*
=> [Improvement] Hookup set as active modal to setApplicantAsActive endpoint

components/admin/requests/physician-assessment/Card.tsx, pages/admin/request/[id].tsx, tools/admin/requests/physician-assessment.ts
[Create PhysicianAssessment Card](https://www.notion.so/uwblueprintexecs/Create-PhysicianAssessment-Card-6241898e4532418d9efef6555fa49dcf)
* Built card and added gql query to fetch required data
**Permanent impairment:**
**"Other" condition + Temporary impairment :**
* I need to confirm 2 minor details, left 2 comments about them and will ask designers on slack
=> [Feature] Create Physician Assessment Card

lib/applications/validation.ts, pages/renew.tsx
[Applicant-Facing Renewal Form Validation](https://www.notion.so/uwblueprintexecs/Applicant-Facing-Renewal-Form-Validation-b1cfebc0af414e6fa54e72fa9503d74c)
* 
*
=> [Feature] Applicant facing renewal form validation

components/admin/requests/additional-questions/EditModal.tsx, lib/applications/validation.ts
[Add form validation to Additional Information Card + EditModal](https://www.notion.so/uwblueprintexecs/Add-form-validation-to-Additional-Information-Card-EditModal-0eb81c83f78541cdae1f6f18dc486bc7)
* 
*
=> [Feature] Additional questions form validation

components/admin/requests/guardian-information/EditModal.tsx, lib/guardian/validation.ts
[Add form validation to Guardian Information Card + EditModal](https://www.notion.so/uwblueprintexecs/Add-form-validation-to-Guardian-Information-Card-EditModal-84872dfc762343e696de7e2f1638d94d)
* 
*
=> [Feature] Edit guardian form validation

components/admin/requests/additional-questions/Card.tsx, components/admin/requests/additional-questions/EditModal.tsx, components/admin/requests/payment-information/Card.tsx, lib/applications/resolvers.ts, lib/applications/schema.ts, lib/applications/validation.ts, lib/graphql/types.ts, tools/admin/requests/additional-questions.ts
[Additional Information Backend Validation](https://www.notion.so/uwblueprintexecs/Additional-Information-Backend-Validation-2e9b5566f3574ec0af0c279549d61065)
* Implemented additional information backend validation in same way as #204 
Example backend form validation error:
=> [Feature] Additional information backend validation

components/form/ValidationErrorAlert.tsx, lib/applications/resolvers.ts, lib/applications/schema.ts, lib/applications/validation.ts, lib/graphql/types.ts, pages/admin/request/create-new.tsx, tools/admin/requests/create-new.ts
[Create New Request Backend Validation](https://www.notion.so/uwblueprintexecs/Create-New-Request-Backend-Validation-8062e10dc68845c58ea924d8686dcbae)
* Closely follows #204 and #206 
Example of backend error being displayed to frontend:
*
=> [Feature] New request backend validation

components/admin/permit-holders/permit-holder-information/Card.tsx, components/admin/permit-holders/permit-holder-information/EditModal.tsx, components/admin/requests/permit-holder-information/Card.tsx, components/admin/requests/permit-holder-information/EditModal.tsx, lib/applicants/resolvers.ts, lib/applicants/schema.ts, lib/applicants/validation.ts, lib/applications/resolvers.ts, lib/applications/schema.ts, lib/graphql/types.ts, tools/admin/permit-holders/permit-holder-information.ts, tools/admin/requests/permit-holder-information.ts
[Personal Information Form Backend Validation](https://www.notion.so/uwblueprintexecs/Personal-Information-Form-Backend-Validation-f5f911bd3d5e4657b34fb8227e12740e)
* Closely follows the implementation of https://github.com/uwblueprint/richmond-centre-for-disability/pull/204
Example of how the backend form validation error is displayed (the error was manually triggered):
*
=> [Feature] Personal Information Form Backend Validation 

lib/applicants/resolvers.ts, lib/applicants/schema.ts, lib/applications/errors.ts, lib/applications/resolvers.ts, lib/graphql/types.ts, tools/applicant/verify-identity.ts
[Add 6 month restricted window for renewal after permit expiry date to applicant renewal flow](https://www.notion.so/uwblueprintexecs/Add-6-month-restricted-window-for-renewal-after-permit-expiry-date-to-applicant-renewal-flow-57af9b1ba0784a02aa4d076d635171ad)
* 
*
=> [Misc] Add 6 month restricted window for applicant renewal

components/form/ValidationErrorAlert.tsx, lib/applicants/validation.ts, lib/applications/resolvers.ts, lib/applications/schema.ts, lib/applications/validation.ts, lib/graphql/types.ts, pages/admin/request/create-renewal.tsx, tools/admin/requests/create-renewal.ts
[Create Renewal Form Backend Validation](https://www.notion.so/uwblueprintexecs/Create-Renewal-Form-Backend-Validation-1c847317c59e453bae76110dfd475594)
* Closely follows the implementation of https://github.com/uwblueprint/richmond-centre-for-disability/pull/204
Backend error:
Example of how the backend form validation error is displayed on frontend (the error was manually triggered):
*
=> [Feature] Create Renewal Form Backend Validation

components/admin/permit-holders/doctor-information/Card.tsx, components/admin/requests/doctor-information/Card.tsx, components/admin/requests/doctor-information/EditModal.tsx, lib/applicants/resolvers.ts, lib/applicants/schema.ts, lib/applications/resolvers.ts, lib/applications/schema.ts, lib/graphql/types.ts, tools/admin/permit-holders/doctor-information.ts, tools/admin/requests/doctor-information.ts
[Doctor’s Information Backend Validation](https://www.notion.so/uwblueprintexecs/ac7b1f636a214a0cbf45f6b76f899b54?v=5414ee5fc5974f149921e192d6eb29b8&p=beb2df3ca482431dad546dbe2a289400)
* Leveraged same code snippet from identify verification 
* Used same Yup Schemas to catch backend errors as in front-end
* Had to do remapping of names in Yup validation for `applications/resolvers.ts`
=> [Feature] Doctor Edit Modal Forms Backend Validation

lib/applicants/validation.ts, lib/applications/validation.ts, lib/guardian/validation.ts, lib/physicians/validation.ts, lib/utils/validation.ts
[Finalize frontend form validation](https://www.notion.so/uwblueprintexecs/Finalize-frontend-form-validation-195501c70b094e9ea63736b1ecd36901)
* Fixed bug where permit holder information on new requests couldn't be saved
* Improved validation of postal codes and phone numbers using regex matching
* No changes implemented for date inputs. I confirmed that the same issue of the dates being prepopulated in new forms is not a new problem as it exists on staging as well, and this problem does not occur when using Chrome.
=> [Fix] Frontend form validation design feedback

components/admin/permit-holders/guardian-information/Card.tsx, components/admin/requests/guardian-information/Card.tsx, components/admin/requests/guardian-information/EditModal.tsx, lib/applicants/field-resolvers.ts, lib/applicants/resolvers.ts, lib/applicants/schema.ts, lib/applications/resolvers.ts, lib/applications/schema.ts, lib/graphql/types.ts, lib/guardian/validation.ts, tools/admin/permit-holders/doctor-information.ts
[Guardian Form Backend Validation](https://www.notion.so/uwblueprintexecs/ac7b1f636a214a0cbf45f6b76f899b54?v=5414ee5fc5974f149921e192d6eb29b8&p=72d09be54a7140538f06d7f5d3e7c2c1)
* Leveraged same code snippet from identify verification
* Used same Yup Schemas to catch backend errors as in front-end
* Front-end has a bug where modal will disappear upon making edit
=> [Feature] Guardian Edit Modal Form Backend Validation

components/admin/requests/reason-for-replacement/Card.tsx, components/admin/requests/reason-for-replacement/EditModal.tsx, components/admin/requests/reason-for-replacement/Form.tsx, lib/applications/resolvers.ts, lib/applications/schema.ts, lib/applications/validation.ts, lib/graphql/types.ts, tools/admin/requests/reason-for-replacement.ts
[Reason For Replacement Form Backend Validation](https://www.notion.so/uwblueprintexecs/Reason-For-Replacement-Form-Backend-Validation-df8f9a30b387469f9ee8c277f328174d)
* Closely follows the implementation of https://github.com/uwblueprint/richmond-centre-for-disability/pull/208
---
Made a few minor fixes that are unrelated to backend validation in https://github.com/uwblueprint/richmond-centre-for-disability/commit/416c83ce6704e2518c7cdd309932ac4e894bc84e
Bugs fixed: 
* Could not update reason to `STOLEN` if it was previously `LOST` because of a frontend validation bug 
* Police file number would not prepopulate if it was previously set
* When updating the reason for a replacement to a different reason, some of the old irrelevant values are still kept in the db (e.g if we update the …
=> [Feature] Reason For Replacement Form Backend Validation

components/applicant/FAQs.tsx, components/applicant/Layout.tsx, pages/index.tsx
[Ticket](https://www.notion.so/uwblueprintexecs/Home-page-fixes-254baeaa881148c98cc381204eddc07c)
Various bug fixes for home page
*
=> [Fix] Home page bug fixes

pages/admin/index.tsx
[Ticket](https://www.notion.so/uwblueprintexecs/Requests-changes-a7bada2073b545d58dd39b0a9b8c1ec3)
*
=> [Fix] Requests fixes

lib/reports/resolvers.ts, tools/admin/reports.ts
[Ticket](https://www.notion.so/uwblueprintexecs/Reports-fixes-4db23dfc79e44973ad21c2fbaf6e3b02)
*
=> [Fix] Reports fixes

components/admin/permit-holders/doctor-information/PreviousDoctorsModal.tsx, lib/applicants/field-resolvers.ts
[Ticket](https://www.notion.so/uwblueprintexecs/Permit-holders-fixes-8a8a02dbf3c444c58b5138095f8241ba)
*
=> [Fix] Permit holders fixes

components/applicant/renewals/IdentityVerification.tsx, components/applicant/renewals/RenewalForm/index.tsx
[Ticket](https://www.notion.so/uwblueprintexecs/Renewal-flow-fixes-78a3b41d020d4869bcd8c922759b90b5)
*
=> [Fix] Renewal form fixes

components/applicant/FAQs.tsx, components/applicant/Layout.tsx, components/applicant/renewals/IdentityVerification.tsx, components/applicant/renewals/RenewalForm/AdditionalInformationSection.tsx, components/applicant/renewals/RenewalForm/ContactInformationSection.tsx, components/applicant/renewals/RenewalForm/DoctorInformationSection.tsx, components/applicant/renewals/RenewalForm/DonationSection.tsx, components/applicant/renewals/RenewalForm/PersonalAddressSection.tsx, components/applicant/renewals/RenewalForm/ReviewSection.tsx, components/applicant/renewals/RenewalForm/index.tsx, pages/index.tsx, tools/theme/breakpoints.ts, tools/theme/index.ts
[Ticket](https://www.notion.so/uwblueprintexecs/Mobile-Screens-Common-Pages-985f244373f94d51b24eae6f181706c6)
* Add mobile responsiveness to applicant-facing screens, including landing page, identity verification, and renewal flow
*
=> [Improvement] Add mobile responsiveness to applicant facing screens

lib/applicants/resolvers.ts, lib/applicants/schema.ts, lib/graphql/types.ts, pages/admin/permit-holders.tsx
[Ticket](https://www.notion.so/uwblueprintexecs/Allow-searching-by-date-of-birth-59a831625e59453abcb166a7da350c3b)
* Add `dateOfBirth` filter to `applicants` resolver
* Add date of birth filter dropdown (+ reorganize) to permit holders table
*
=> [Feature] Add date of birth filter to permit holders page

lib/application-processing/resolvers.ts
[Ticket](https://www.notion.so/uwblueprintexecs/Fix-replacement-application-expiry-date-38cc9e0cd0d0419a900d5d85dd4d2623)
* Set replacement application expiry date to the expiry date of the permit being replaced
* Add validation to ensure that most recent permit exists and has expiry date in the future
* Invalidate permit being replaced
*
=> [Fix] Fix replacement application expiry date

next.config.js
[Ticket](https://www.notion.so/uwblueprintexecs/Disable-access-to-GQL-playground-on-prod-217d3847229c46b5bab34538834f5819)
* 
*
=> [Fix] Remove GQL playground redirect

pages/404.tsx, pages/500.tsx, pages/api/payment-received.ts
N/A
* Add error logging to Shopify webhook
* Add 404 and 500 pages
*
=> [Improvement] Various fixes

pages/index.tsx
[Ticket](https://www.notion.so/uwblueprintexecs/Fix-RCD-emails-on-homepage-3caeea88bc0644a0b994c2f6cbf0546f)
* 
*
=> [Fix] Fix homepage RCD emails

lib/applicants/utils.ts, lib/graphql/apollo.ts, pages/404.tsx, pages/500.tsx, pages/api/payment-received.ts, pages/index.tsx
* [Fix] Get most recent permit by latest expiry date (#248)
* [Fix] Fix homepage RCD emails (#247)
* [Improvement] Various fixes (#246)
* [Fix] Remove GQL playground redirect (#245)
* [Fix] Disable GraphQL playground in production (#244)
*
=> [Release] Version 0.0.2

components/admin/permit-holders/app-history/Card/AppHistoryRecord.tsx, components/admin/requests/Header.tsx, lib/applications/resolvers.ts, pages/admin/request/[id].tsx, tools/admin/requests/view-request.ts
N/A
* Copy changes for request page
* On request page, show permit expiry date instead of expected expiry date for completed applications
*
=> [Fix] Fix various applications issues

components/admin/permit-holders/app-history/Card/AppHistoryRecord.tsx, components/admin/requests/Header.tsx, lib/applications/resolvers.ts, pages/admin/request/[id].tsx, tools/admin/requests/view-request.ts
* [Fix] Fix various applications issues (#250)
*
=> [Release] Version 0.0.3

components/admin/permit-holders/app-history/Card/AppHistoryRecord.tsx, components/admin/permit-holders/current-application/Card/Header.tsx, components/admin/permit-holders/current-application/Card/MedicalInformationSection.tsx, components/admin/permit-holders/medical-history/Modal.tsx, components/admin/requests/Header.tsx, components/admin/requests/create/SelectedPermitHolderCard.tsx, components/admin/requests/permit-holder-information/Card.tsx, components/admin/requests/processing/TaskStep.tsx, components/admin/requests/reason-for-replacement/Card.tsx, lib/invoices/utils.ts, lib/reports/resolvers.ts, lib/utils/date.ts, pages/admin/index.tsx, pages/admin/permit-holders.tsx
[Ticket](https://www.notion.so/uwblueprintexecs/Make-date-formatting-consistent-across-app-49015b8773124a03888a025004487dd8)
* Standardize date formatting to `YYYY-MM-DD` across app
*
=> [Fix] Standardize date formatting

components/admin/permit-holders/app-history/Card/AppHistoryRecord.tsx, components/admin/permit-holders/current-application/Card/Header.tsx, components/admin/permit-holders/current-application/Card/MedicalInformationSection.tsx, components/admin/permit-holders/medical-history/Modal.tsx, components/admin/requests/Header.tsx, components/admin/requests/create/SelectedPermitHolderCard.tsx, components/admin/requests/permit-holder-information/Card.tsx, components/admin/requests/processing/TaskStep.tsx, components/admin/requests/reason-for-replacement/Card.tsx, lib/applicants/resolvers.ts, lib/invoices/utils.ts, lib/reports/resolvers.ts, lib/utils/date.ts, pages/admin/index.tsx, pages/admin/permit-holders.tsx, tools/admin/reports.ts
* [Improvement] Split address fields in permit holders report (#253)
* [Fix] Restrict permit expiry filter to only active permits (#254)
* [Fix] Standardize date formatting (#252)
*
=> [Release] Version 0.0.4

lib/applicants/resolvers.ts
* [Fix] Show applicants even if they do not have an active permit (#256)
*
=> [Release] Version 0.0.5

lib/application-processing/resolvers.ts
[Ticket](https://www.notion.so/uwblueprintexecs/Issue-creating-invoice-record-af2f8902437c4f23a8f66bb66ac52a1b)
* Invoice record creation was failing because we were using the application ID to link the created invoice to an application processing record (wrong value)
*
=> [Fix] Fix invoice records failing to be created

lib/reports/resolvers.ts
[Ticket](https://www.notion.so/uwblueprintexecs/Accountant-Report-Error-6f3c01e9e0b84ebcbe849c0174c6e11f)
* Accountant report aggregation values for day-by-day data was incorrect to an incorrect bound on the DB query
*
=> [Fix] Fix accountant report aggregation values

lib/applications/field-resolvers.ts
[Ticket](https://www.notion.so/uwblueprintexecs/Task-Log-Not-Showing-bb8aaa663c7a499dadce2970eaa97fd6)
* Task log entries were not showing because employee data was not being fetched for the task log tasks
*
=> [Fix] Fix task log entries not showing

components/applicant/renewals/RenewalForm/ContactInformationSection.tsx, components/applicant/renewals/RenewalForm/PersonalAddressSection.tsx, components/applicant/renewals/RenewalForm/index.tsx, lib/application-processing/resolvers.ts, lib/applications/field-resolvers.ts, lib/applications/resolvers.ts, lib/reports/resolvers.ts, pages/admin/permit-holders.tsx, tools/admin/requests/create-new.ts
* [Fix] Fix create new APP flow failing (#263)
* [Fix] Fix task log entries not showing (#262)
* [Fix] Fix inconsistent applicant flow copy (#261)
* [Fix] Fix accountant report aggregation values (#260)
* [Fix] Fix invoice records failing to be created (#259)
* [Fix] Fix permit holders not rendering if no recent permit (#258)
*
=> [Release] Version 0.0.6

lib/graphql/apollo.ts
=> [Fix] Re-enable GQL playground for debugging

lib/graphql/apollo.ts
N/A
* (title) for debugging on staging
*
=> [Fix] Allow GQL introspection

.github/workflows/ci.yml, package.json
=> [Fix] Specify node version in package.json

CONTRIBUTING.md
Added a CONTRIBUTING.md file as per conversation with @OustanDing.
=> [Docs] BSF CONTRIBUTING.md

docker-compose.yml
N/A
New docker-compose.yml file to create a local PostgreSQL instance (mostly copied from starter-code-v2).
See Discord for the new .env variables that are required.
To test:
1. Ensure that you do not have an existing instance of PostgreSQL running on localhost
2. Run `docker-compose up --build` from project root
3. Once you see the "database system is ready to accept connections" log message, test DB connection by running a psql shell
```
docker exec -it rcd_db /bin/bash -c "psql -U postgres -d rcd"
```
=> [Chore] Create docker-compose.yml file for local PostgreSQL instance

components/admin/requests/reason-for-replacement/Card.tsx, lib/reports/resolvers.ts, lib/utils/date.ts, pages/admin/index.tsx
* [Fix] Fix time zone for requests and reports (#278)
*
=> [Release] Version 0.0.7

components/admin/requests/Header.tsx
[Ticket](https://www.notion.so/uwblueprintexecs/Some-time-zones-are-still-EST-8984f93c38da4fccab00a9b510cade56)
* Use new local time YYYY-MM-DD date formatter in the header component
* N/A
=> [Fix] Fix time zone bug in requests header

components/admin/requests/Header.tsx
* [Fix] Fix time zone bug in requests header (#281)
* N/A
=> [Release] Version 0.0.8

components/applicant/renewals/IdentityVerification.tsx
[[8] Add User Id](https://www.notion.so/uwblueprintexecs/8-Add-User-Id-8b26734c66174033bc0ae456ad2cf737?pvs=4)
* 
*
=> [Fix] Update User ID copy

tools/admin/admin-management/graphql/delete-employee.ts
[Ticket](https://www.notion.so/uwblueprintexecs/7-Admin-management-page-user-deletion-not-working-0d2e4cf9a2cc4f00a3928ab9d0ad2d29)
* Fix input format in GQL delete employee mutation
* N/A
=> [Fix] Fix the GraphQL delete employee mutation

components/applicant/FAQs.tsx
[Broken contact us link](https://www.notion.so/uwblueprintexecs/15-Broken-link-on-the-main-APP-webpage-1ff73743f9a04fe9bbcb0fd18182e3fb)
* Replaced old link with https://rcdrichmond.org/ContactUs/ContactUs.php
* N/A
=> [Fix] Broken contact us link

package.json
* This should ideally fix the broken Shopify payments on prod
*
=> Update Shopify version from 2.13.0 to 2.20.0

yarn.lock
N/A
* Update shopify-buy version in yarn.lock
* N/A
=> Update shopify-buy in yarn.lock

pages/index.tsx
N/A
* Update form links (taken from https://www.rcdrichmond.org/Parking/ParkingPermit.php)
* N/A
=> [Fix] Update form links to reflect new processing fee

components/admin/requests/processing/TasksCard.tsx, lib/application-processing/resolvers.ts
[[21] Move Wallet Card button in application processing](https://www.notion.so/uwblueprintexecs/21-Move-Wallet-Card-button-in-application-processing-de566b58405a4ccda52606e3caacbda7)
* Adjust order of wallet card processing task to be below document upload
https://github.com/uwblueprint/richmond-centre-for-disability/assets/77544794/1494cf75-89a1-4010-8b07-aded32e7b123
=> [Fix] Move wallet card task in application processing

components/admin/requests/permit-holder-information/Card.tsx, lib/applicants/validation.ts
[Fix otherGender form validation](https://www.notion.so/uwblueprintexecs/Fix-otherGender-form-validation-4fd4026dbff54764b1d297485613793c)
* Follow up to #318
=> [Fix] Fix validation schema for other gender field

prisma/dev-seed-utils/employees.ts
* Add Keane to dev seeding script
=> [Misc] Add new contributor to seeding script

pages/index.tsx
* Add banner for upcoming database maintenance
=> [Misc] Add maintenance banner

pages/index.tsx
* [Misc] Add maintenance banner (#329)
=> [Release] Version 0.1.0

components/admin/requests/processing/TasksCard.tsx
[Change text on processing task 2](https://www.notion.so/uwblueprintexecs/Change-text-on-processing-task-2-c636b9111ab14385b10fd338896b7696)
* Remove the word gender from processing task 2 as it is no longer on permit placards
=> [Fix] Change text on processing task 2

pages/index.tsx
* Remove holiday closure banner from #336
=> [Misc] Remove holiday closure banner

lib/invoices/utils.ts
[Generated donation receipts have an alignment issue](https://www.notion.so/uwblueprintexecs/Generated-donation-receipts-have-an-alignment-issue-6469943542ff4b898ea6c36a0841cd9c?pvs=4)
* 
*
=> [Fix] Generated donation receipts have an alignment issue

components/admin/requests/payment-information/Form.tsx, lib/graphql/schema.ts, lib/graphql/types.ts, lib/reports/resolvers.ts, lib/scripts/oneoff/backup/populate-db-09-13-21.ts, lib/scripts/oneoff/populate-db-09-13-21.js, lib/scripts/oneoff/populate-db-10-01-2021.js, prisma/migrations/20231123031908_init/migration.sql, prisma/schema.prisma, prisma/schema.sql
[Add Amex as payment method](https://www.notion.so/uwblueprintexecs/Add-Amex-as-payment-method-8bd27cab67a34fe9b76affbb9922bff1)
* Added `AMEX` in all the locations of other payment methods
* We need to run migrations after deployment
=> [Feature] Add AMEX

prisma/migrations/20231123031908_init/migration.sql, prisma/migrations/20240207054756_add_amex_payment_type/migration.sql
N/A
As titled
```
npx prisma migrate dev --name add_amex_payment_type --create-only
```
Inspect the generated migration file to see if change is as expected, then apply migration to local DB using
```
npx prisma migrate dev
```
=> [Fix] Revert init migration file and add new migration for AMEX paymenttype

prisma/dev-seed-utils/employees.ts
=> [Improvement] Add Matthew to employee.ts

prisma/dev-seed-utils/employees.ts
=> Add Sharujan to employees.ts

components/applicant/Layout.tsx, lib/invoices/utils.ts
[New Address](https://www.notion.so/uwblueprintexecs/New-Address-f49c8a9768d84d8189b04f4eef48312f)
* RCD requesting change to new address (https://www.rcdrichmond.org/NewsAndEvents/2024_Interim_Relocation/WeAreMoving_PostMove_banner.pdf)
1. Follow request approval flow.
2. Verify the generated invoice and donation receipt PDF has the new address.
The steps are outlined in the video below:
<video src=https://github.com/uwblueprint/richmond-centre-for-disability/assets/77544794/2dc5582d-854e-44f9-8251-ffb265dc4d89>
=> [Misc] Change address from unit 842 to 968

components/admin/requests/reports/GenerateModal.tsx, lib/graphql/types.ts, lib/reports/resolvers.ts, lib/reports/schema.ts, tools/admin/reports.ts
[Add tax receipt and invoice receipt category to application report](https://www.notion.so/uwblueprintexecs/Add-tax-receipt-and-invoice-receipt-category-to-application-report-44dfe1caed6f46e7bf3f2f9292e1b6f8)
* Add invoice receipt number from invoice PDF to application reports
* <img width="297" alt="invoice-receipt" src="https://github.com/uwblueprint/richmond-centre-for-disability/assets/77544794/644a5942-0ff5-4a1b-9bc5-9adcaf1d5cbd">
* Add tax receipt number from donation PDF to application reports
* <img width="322" alt="tax-receipt" src="https://github.com/uwblueprint/richmond-centre-for-disability/assets/77544794/86fd04ec-fe70-4cea-97c7-f58d2de103e8">
1. Set the donation amount for a new request to be at least $20.
2. Process the request by following the steps in the flow.
3. Save …
=> [Feature] Add receipt numbers to application reports

prisma/dev-seed-utils/employees.ts
=> Add Jenny to employees

pages/admin/request/create-renewal.tsx
[Unsaved Doctor's Info](https://www.notion.so/uwblueprintexecs/RCD-Unsaved-Doctor-s-Info-24ec0f0463644648bfd3351be733ce46?pvs=4)
* changed the `physicianFirstName,  physicianLastName, ...` to use the `values.doctorInformation` instead of the global state variable `doctorInformation`,.
* **I'm not entirely sure why this works. Still working on figuring it out**
**Loom Demo of it working** https://www.loom.com/share/a66659ce40674003a663f2e43720d142
=> [Fix] Unsaved Doctor's Information

prisma/dev-seed-utils/employees.ts
=> Add Brayden to employee.ts

prisma/migrations/20241029021622_updated_at_for_renewalapp/migration.sql, prisma/schema.prisma
[[RCD] updatedAt of replacement application not being changed](https://www.notion.so/uwblueprintexecs/RCD-updatedAt-of-replacement-application-not-being-changed-d15363a51033406d81f58cdbf357d013?pvs=4)
* added the `@updatedAt` attribute to the ReplacementApplication model.
- demo is below
- https://www.loom.com/share/43e53cee45f948b0b69813e240b1bd94
=> [Fix] updatedAt for Replacement Application fixed

prisma/dev-seed-utils/employees.ts
N/A
* Add David to employee.ts
* N/A
=> Add David to employee.ts

.github/workflows/ci.yml
=> Update GitHub Actions to use v4 cache/actions
