lib/applicants/errors.ts
lib/applicants/resolvers.ts
lib/applicants/schema.graphql
lib/employees/schema.graphql
lib/graphql/resolvers.ts
lib/graphql/scalars.ts
lib/graphql/schema.graphql
lib/graphql/types.ts
prisma/index.ts

- Adds GraphQL Queries + Mutations for Applicants (createApplicant mutation, applicants query)
- Adds Date scalar to GraphQL Schema (e.g. dateOfBirth, certificationDate, etc.)
This date scalar consumes an integer in milliseconds (Unix Time), represents it as a JavaScript Date object on the back-end, and serializes it as an integer in milliseconds (Unix Time)
TODO: Blocked on integrating with other tables (ApplicantStatus, Application, Guardian, MedicalInformation, Permit)

Setup GraphQL queries and mutations for applicants

---

package.json
yarn.lock

Next.js runs ESlint during builds - we were missing the `eslint-config-next` dev dependency for this to take place

[Misc] Install eslint-config-next dev dependency

---

lib/db/errors.ts
lib/graphql/resolvers.ts
lib/graphql/schema.graphql
lib/graphql/types.ts
lib/physicians/errors.ts
lib/physicians/resolvers.ts
lib/physicians/schema.graphql

- Added physician queries and mutations
I deviated a bit from the error handling section that's [on notion](https://www.notion.so/uwblueprintexecs/Development-processes-a0313f2bef9941fc8752c8e7b5be5e70#9e88e7b5ccb44f798d09b665845092a1) for a couple reasons which I commented on. Still not 100% sure it's the best way to go in this case so would love some feedback on that
Mutation:
Query
Errors:
Duplicate MSP
Length Constraint

[Feature] Graphql endpoints for the physician model

---

lib/applicants/resolvers.ts
lib/physicians/resolvers.ts
lib/utils/format.ts

[Function for formatting db fields](https://www.notion.so/uwblueprintexecs/Function-for-formatting-DB-fields-887ec602da7043539495d87bfa44871f)
* added formatting functions for phone number and postal codes under `lib/utils/format.ts` which remove extra characters from these fields
* called these functions in applicant and physician resolvers
* Some sort of data validation should probably be done before formatting, didn't put it in this PR to keep things concise 
* any other formatting that should be done before saving?

[Feature] Add formatting functions for phone number and postal code

---

components/applicant/Layout.tsx
components/applicant/renewals/IncompleteSectionAlert.tsx
components/applicant/renewals/ReviewRequestField.tsx
components/applicant/renewals/TOSModal.tsx
components/internal/Layout.tsx
package.json
pages/index.tsx
pages/renew.tsx
pages/verify-identity.tsx
tools/components/Steps/useSteps.ts
tools/theme/components/alert.ts
tools/theme/index.ts
yarn.lock

[Ticket](https://www.notion.so/uwblueprintexecs/Build-TOS-User-Validation-Renewal-Form-b6d27633acfe44fd9cd948dee8fc0554)
* Created frontend UI with basic UX for applicant renewal flow
* Created a reusable `ReviewRequestField` component to for the "review request" section - this can also be used for the replacement flow in the near future
* The provided `useSteps` hook for controlling the stepper stake lacked a "go to step" function, which we need for jumping to previous steps to edit them. I made a custom `useSteps` hook in `tools/components/Steps/useSteps.ts` which is very similar to the hook provided by `chakra-ui-steps`, but with this extra functionality
* This ticket only includes the frontend building of the applicant renewal flow. There is no form submission or validation. Also, …

[Feature] Renewal Flow Frontend

---

.eslintrc.json
README.md
components/internal/Table.tsx
pages/admin/index.tsx
prisma/schema.prisma
tools/components/internal/table.ts
tools/types.ts
types/react-table-config.d.ts

[Ticket](https://www.notion.so/uwblueprintexecs/Add-Table-sorting-94f1d6e461fc49cf800d6305e8b50d12)
* Added sorting frontend to `Table` component (on clicking header, render the arrow)
* Added `onChangeSortOrder` callback function prop to the `Table` component
* Added `getSortOptions` function that takes the `sortBy` state returned by React Table and returns an array of `[<column value>, SortOrder]` tuples that we will use in our GQL APIs
* Needed to implement `react-table-config.d.ts` declaration file to add sorting types to React Table initialization options

[Improvement] Add Table sorting

---

components/internal/Pagination.tsx
pages/admin/index.tsx

[Ticket](https://www.notion.so/uwblueprintexecs/Build-Pagination-component-f32bfb9913474fd1ba32a32213122fd6)
* Built `Pagination` component for handling pagination of `Table` components. Pagination is handled server-side, so GQL data refetching should be done in the `onPageChange` callback parameter
* Added `Pagination` component to Requests table page
* The original ticket required many fields that I realized were unnecessary, as the functionality could be abstracted in the `Pagination` component
* The `usePagination` hook is not necessary - again, all of the functionality could be abstracted inside the `Pagination` component

[Feature] Build Pagination component

---

lib/graphql/resolvers.ts
lib/graphql/schema.graphql
lib/graphql/types.ts
lib/physicians/resolvers.ts
lib/physicians/schema.graphql
prisma/schema.prisma

[Ticket](https://www.notion.so/uwblueprintexecs/Create-upsertPhysician-GQL-API-85d6344d27d540fb89702f9dfa413d45)
* Added the `upsertPhysician` GraphQL API for upserting physicians
* This will be useful for processing the physician input in completed applications. We want to upsert the physician upon application completion.

[Feature] Create upsertPhysician GQL API

---

components/internal/PermitHolderInfoCard.tsx
lib/applicants/errors.ts
lib/applicants/resolvers.ts
lib/applicants/schema.graphql
lib/applications/resolvers.ts
lib/db/errors.ts
lib/graphql/authorization.ts
lib/graphql/resolvers.ts
lib/graphql/schema.graphql
lib/guardian/resolvers.ts
lib/guardian/schema.graphql
lib/medicalInformation/resolvers.ts
lib/medicalInformation/schema.graphql
lib/permits/resolvers.ts
lib/physicians/errors.ts

[Ticket](https://www.notion.so/uwblueprintexecs/Create-updateApplicant-GQL-API-65f80cca22394cb48c315452bada044e)
* Original ticket asks for `updateApplicant` GQL API that also encompasses updating medical information and guardian. However, granularity is preferred as the three categories are edited separately in the user flows. As a result, built the `updateApplicant` (for core applicant data), `updateMedicalInformation` (for applicant medical info) and `updateGuardian` (for applicant guardian) APIs
* Modified the `createApplicant` GQL API to also create the medical information and guardian records for the created applicant. This ensures that every applicant has medical information and guardian records and keeps our data in sync. It is not possible to create a medical information or …

[Feature] Build GQL APIs for updating applicant data, improve GQL API for creating applicant

---

components/internal/PermitHolderInfoCard.tsx
components/internal/RequestStatusBadge.tsx
components/internal/modals/EditPermitHolderInformationModal.tsx
components/permit-holders/AppHistoryCard.tsx
components/permit-holders/AttachedFilesCard.tsx
components/permit-holders/DoctorInformationCard.tsx
components/permit-holders/GuardianInformationCard.tsx
components/permit-holders/MedicalHistoryCard.tsx
components/permit-holders/PermitHolderHeader.tsx
components/permit-holders/PersonalInformationCard.tsx
components/permit-holders/SuccessfulEditAlert.tsx
components/permit-holders/modals/EditUserInformationModal.tsx
components/permit-holders/modals/MedicalHistoryModal.tsx
components/permit-holders/modals/PreviousDoctorsInformationModal.tsx
components/requests/modals/EditDoctorInformationModal.tsx
pages/admin/permit-holder/[permitHolderId].tsx
tools/theme/colors.ts
tools/theme/components/badge.ts

[View individual Permit Holder page](https://www.notion.so/uwblueprintexecs/View-individual-Permit-Holder-page-396f2b4450ee4b30bab184678d5768da)
Demo:
* Making guardian information editable has been deprioritized for the MVP and will be addressed post-mvp so the edit guardian  modal was not built (clicking the edit button on the guardian information card does nothing)
* Alerts that pop up at the bottom after editing should be closable, I couldn't figure out how to make it closable and just removed the close button and added a ticket to the task board.
* The way data is handled in the components will likely change to match API response data

[Feature] Build view individual permit holder page

---

components/internal/Pagination.tsx

None
* `Pagination` component was broken. The Next button was not being disabled when `totalCount=0`. This was because we calculated as the number of pages as `ceil(totalCount / pageSize)`, which would give 0. When checking whether we were on the last page, we were checking if `pageNumber === lastPage - 1` which was -1 - never possible.

[Bugfix] Fix Pagination component next button not being disabled when totalCount=0

---

components/DatePicker.tsx
components/DateRangePicker.tsx
pages/admin/permit-holders.tsx
pages/verify-identity.tsx

[Ticket](https://www.notion.so/uwblueprintexecs/Replace-date-picker-on-Verify-Identify-page-with-React-date-picker-component-6e7d21e4985a4d6e9e7597e3d39685bf)
* Created `DatePicker` component that wraps `DayPickerInput` component from `ReactDayPicker`, replaced date input with this new component in the verify identity page of the renewal flow
*

[Improvement] Replace verify identity page date input with DatePicker component

---

.gitignore
components/requests/PersonalInformationCard.tsx
lib/applicants/field-resolvers.ts
lib/applicants/schema.ts
lib/graphql/types.ts
lib/scripts/oneoff/backup/populate-db-09-13-21.ts
lib/scripts/oneoff/populate-db-09-13-21.js
package.json
prisma/dev-seed-utils/applicants.ts
prisma/dev-seed-utils/application-processings.ts
prisma/dev-seed-utils/applications.ts
prisma/dev-seed-utils/guardians.ts
prisma/dev-seed-utils/medical-information.ts
prisma/dev-seed-utils/permits.ts
prisma/dev-seed-utils/physicians.ts
prisma/schema.prisma
prisma/schema.sql
prisma/types.ts
yarn.lock

[Ticket](https://www.notion.so/uwblueprintexecs/Add-sample-data-to-staging-database-1716f8617a7d46f291c2ad62a621afa4)
* Create data population script
* Small changes to seeding functions (removed unnecessary console logs)
* Overloaded seeding functions to support custom seeding data - this could be useful in the future for our data migration
* Small bug fix for linking request name to permit holder page (it was redirecting to `/permit-holder/...` instead of `/admin/permit-holder/...`
* Populated staging database
* `ts-node` wasn't working with the script I wrote. In the interest of time, I converted it to JS. This should be okay since it's a oneoff and we can address this in the future
* Staging permit holder table page is down right now - requires merging this ticket to implement new …

[Misc] Add sample data to staging database

---

lib/applicants/schema.ts
lib/graphql/types.ts

[Ticket](https://www.notion.so/uwblueprintexecs/View-Permit-Holder-only-displaying-attached-files-card-3958b57515164eb791d70a7e584e2a90)
* The cards weren't rendering because of a schema-related GraphQL error. Recently, we changed the `Applicant` schema such that `guardianId` is nullable, since permit holders don't necessarily need to have guardians. However, `guardian` was still a non-null field but that was not updated in the schema. Our `applicant` resolver was failing on applicants that didn't have guardians.
* The fix was simply to update the `Applicant` schema to make the `guardian` field nullable.
* Left a TODO. The `CreateApplicantInput` input schema should have `guardian` be optional. This also requires a resolver update. In the interest of time for MVP handoff, this will be …

[Fix] Fix View Permit Holder page not rendering any cards

---

lib/scripts/oneoff/populate-db-09-13-21.js
prisma/dev-seed-utils/applicants.ts
prisma/dev-seed-utils/application-processings.ts
prisma/dev-seed-utils/applications.ts
prisma/dev-seed-utils/guardians.ts
prisma/dev-seed-utils/medical-information.ts
prisma/dev-seed-utils/permits.ts
prisma/dev-seed-utils/physicians.ts
prisma/dev-seed-utils/replacements.ts

[Ticket](https://www.notion.so/uwblueprintexecs/Permit-Holders-Page-not-displaying-user-ID-properly-e738ca3a37ea4b7da231d0cc4ff7c9c3)
* Please see Notion ticket for screenshot of issue. When seeding data, for the `create` parameter, some of the unique keys were omitted. This caused the seeded data to be missing the unique keys. RCD user ID was one of the missing keys. Also preemptively fixed other potential instances of missing columns.
* Need to reseed staging database

[Fix] Fix seeded users not having RCD user ID

---

components/requests/modals/EditDoctorInformationModal.tsx
lib/graphql/types.ts
lib/medical-information/resolvers.ts
lib/medical-information/schema.ts
lib/physicians/resolvers.ts
lib/physicians/schema.ts
pages/admin/permit-holder/[permitHolderId].tsx
tools/pages/admin/permit-holders/update-medical-information.tsx
tools/pages/admin/permit-holders/upsert-physician.ts

[Resolve physician update failing in View Permit Holder page](https://www.notion.so/uwblueprintexecs/Resolve-physician-update-failing-in-View-Permit-Holder-page-3dab29ed46204525a7aa9849d5b60ed2)
* When the Doctor's MSP number is updated through the edit doctor's information modal on the permit holder page, upset physician will create a new Physician in the DB. We then also call an `updateMedicalInformation` mutation to point the applicant's medical information to the new physician.
* Currently the past physicians list from an applicant's medical history is not being updated properly with new physicians. The past physicians are being read from the list of applicant's past applications, so when a new physician is created in through this edit doctor modal, it will not appear in the list of …

[Fix] Update physician on permit holder page when MSP is updated

---

pages/admin/index.tsx
pages/admin/permit-holders.tsx
tools/pages/admin/index.ts
tools/pages/permit-holders/permit-holders-table.ts

[User ID displaying wrong field in tables](https://www.notion.so/uwblueprintexecs/User-ID-displaying-wrong-field-in-tables-3b070960332e4cecb40948169fc3d5f3)
* Return `rcdUserId` instead of `applicantId` in `GET_APPLICATIONS_QUERY` and `GET_PERMIT_HOLDERS_QUERY` and pass to table
* Show "N/A" in table for the ID if the `rcdUserId` does not exist.

[Fix] Show correct rcdUserId in requests and permit holders tables

---

lib/employees/resolvers.ts
lib/graphql/resolvers.ts
lib/graphql/schema.ts
lib/graphql/types.ts

[Get Employee Endpoint](https://www.notion.so/uwblueprintexecs/ac7b1f636a214a0cbf45f6b76f899b54?v=5414ee5fc5974f149921e192d6eb29b8&p=98582f0df40b4e67866b6e9f456b6b81)
Normal Query:
Null Case:

[Feature] Get Employee Endpoint

---

lib/applicants/resolvers.ts
lib/applications/resolvers.ts

[Requests Table search by user ID not working](https://www.notion.so/uwblueprintexecs/Requests-Table-search-by-user-ID-not-working-7e0fcd020c51498f987c9afc11864cb3)
* Changed the `applications` resolver to filter by the `rcdUserId` column instead of the `id` column of the `applicants` table
* Made variable names more clear to avoid confusion in the future
* I might be missing some context but I'm not sure why the applications resolver was looking at the `applicants` table to begin with. Are there any implications of filtering by the `rcdUserId` field in the `applications` table instead?

[Fix] Requests Table search by user ID not working

---

components/admin-management/ConfirmDeleteAdminModal.tsx
pages/admin/admin-management.tsx
tools/pages/admin-management/types.ts
tools/theme/colors.ts

[Ticket](https://www.notion.so/uwblueprintexecs/Delete-Users-Modal-frontend-80f3ad345b8043ebb40869dd96b12bb5)
* Built confirm delete admin modal using Chakra UI `AlertDialog` component
* Implemented modal in Admin Management page such that clicking on "Delete User" in a user's menu opens the modal
* Clicking "Cancel" or in the modal overlay will close the modal
* Clicking "Delete" will simply close the modal for now. Need to implement delete functionality in future API hookup
* Needed to move column configuration to inside the `AdminManagement` component so that clicking the options menu could affect the component state
* Note that when opening the modal, the "Cancel" button is automatically focused. This is to make it harder for keyboard users to accidentally delete the admin
Updated …

[Feature] Build confirm delete admin modal

---

tools/pages/permit-holders/permit-holders-table.ts

[Ticket](https://www.notion.so/uwblueprintexecs/Fix-permit-holders-table-redirecting-to-undefined-page-6a87255c7a1b4ca483291054b44ebb95)
* In https://github.com/uwblueprint/richmond-centre-for-disability/pull/65, we removed the `id` field from the permit holders GraphQL query. Thus, every permit holder row did not have an `id` field so when redirecting to the individual permit holder pages, the permit holder ID was undefined so the page didn't fully load.

[Fix] Add applicant ID back to permit holders table GraphQL query

---

lib/applicants/schema.ts
lib/graphql/types.ts
prisma/schema.prisma
prisma/schema.sql

[Add inactive_reason to applicant schema](https://www.notion.so/uwblueprintexecs/Add-inactive_reason-to-applicant-schema-d30de2632d7344508132f231ed8b2d21)
* Added `inactive_reason` field to applicant sql schema, and `Applicant` and `UpdateApplicantInput` graphql types

[Improvement] Add inactive reason to applicant schema

---

pages/verify-identity.tsx

[Change error message to toast on User Validation Page in application flow](https://www.notion.so/uwblueprintexecs/Change-error-message-to-toast-on-User-Validation-Page-in-application-flow-e0d01ef9bc9844539db1452b7ec5869b)
* Took out the Alert component and added logic to the onCompleted callback to show toast instead
*

[Fix] Replace Alert component with toast

---

lib/application-processing/errors.ts
lib/application-processing/resolvers.ts
lib/application-processing/types.ts

[Ticket](https://www.notion.so/uwblueprintexecs/Completing-an-application-fails-af0dddbcc9aa433195ae1775744c5124)
* Having a guardian is no longer required for applicants and applications, so when attempting to mark an application as completed, the nested guardian update would fail for applicants that don't have a guardian. Added conditional logic to handle cases wherein guardian fields are complete/incomplete and the case where an applicant does not have a guardian.

[Fix] Fix completing application failing for users with guardians

---

lib/employees/resolvers.ts
lib/employees/schema.ts
lib/graphql/schema.ts
lib/graphql/types.ts
pages/admin/admin-management.tsx
tools/pages/admin/admin-management/delete-employee.ts
tools/pages/admin/admin-management/types.ts

[Admin Management Table API Hookup - Delete admin](https://www.notion.so/uwblueprintexecs/Admin-Management-Table-API-Hookup-Delete-admin-05121d7aff88479691d2155c1c5dcc84)
* Created the gql delete admin mutation 
* hooked the api up to the delete admin modal
* added `notifyOnNetworkStatusChange` to the getEmployees useQuery hook to update the admin-management table upon deletion
* Made a slight change to the deleteEmployee resolver to make sure the ID is recieved through args and it is parsed to be an integer
* Will add comments to added code later 
* Lines 142 and 143 in `admin-management.tsx` are not fixed because that would be part of the update api hookup ticket. Not sure if I should fix it in this PR, would like a second opinion pls!

[Feature] Admin Management Table API Hookup

---

components/admin/requests/PaymentInformationCard.tsx
components/admin/requests/forms/PaymentDetailsForm.tsx
components/admin/requests/modals/EditPaymentDetailsModal.tsx
pages/admin/request/[id].tsx
tools/components/admin/requests/forms/types.ts

[New Renewal Request Form Payment Card Section](https://www.notion.so/uwblueprintexecs/ac7b1f636a214a0cbf45f6b76f899b54?v=5414ee5fc5974f149921e192d6eb29b8&p=884f93c751444b6ca9e954d35d0cd3b5)
* Removed Large State Field and Connected it to Single Object - `PaymentDetailsData`
* Wired State as Updated On Open with `useEffect` as well as on API changes (accounts for Saving)
* Created Custom `PaymentDetailsForm` Component for PaymentDetails to be accessed elsewhere.
* Oustan Ding will probably explain the flow of this modal for other modals following up.

[Improvement] Refactor and Extract State from Payment Card Section

---

lib/applicants/resolvers.ts
lib/applications/resolvers.ts

[Add ability to search with part of name/substring](https://www.notion.so/uwblueprintexecs/Add-ability-to-search-with-part-of-name-substring-9a5cd7aa010c412a8373e90c676b4a65)
* Quick fix: change `equals` to `startsWith` in applicants and applications resolvers
***
* This change is for first, middle, and last name so a search for `"App T"` will match `Applicant Three` but not `Applicant One`

[Improvement] Add ability to search with part of name/substring

---

pages/admin/reports.tsx

[Build Accounting Report Page Frontend](https://www.notion.so/uwblueprintexecs/Build-Accounting-Report-Page-Frontend-5ab4715f071548e699280dae5e3807a8)
* Had to switch date pickers with HTML date pickers 
* Added a setTimeout function to show loading state for 3 seconds before displaying the result screen
* Switching date pickers changed the design of the Report box as well as the formatting of the date when displayed ( dashed instead of slashes)

[Feature] Build Accounting Report Page Frontend

---

components/admin/requests/ReasonForReplacementCard.tsx
components/admin/requests/forms/ReasonForReplacementForm.tsx
components/admin/requests/modals/EditReasonForReplacementModal.tsx
tools/components/admin/requests/forms/types.ts

[New Replacement Request - Extract Reason for Replacement Card](https://www.notion.so/uwblueprintexecs/New-Replacement-Request-Extract-Reason-for-Replacement-Card-56986c1d5b0245deae4996e9860b7e3e)
* Extracted the form fields from the `EditReasonForReplacementModal` component (which is essentially all the content inside the `ModalBody`) into the new `ReasonForReplacementForm`  component
* Created `ReasonForReplacement` in `tools/components/admin/requests/forms/types.ts` to hold form fields data
Implementation closely follows Emilio and Anish's extraction PRs
* See comment

[Improvement] Extract Reason for Replacement Card

---

components/Typeahead.tsx
components/admin/permit-holders/PermitHolderTypeahead.tsx
lib/utils/format.ts
pages/admin/index.tsx

[Typeahead component hookup](https://www.notion.so/uwblueprintexecs/Typeahead-component-hookup-4d8df6195c554ac1ad7dff7d8cfea260)
* Uses `Typeahead` component, and uses existing permit holders GQL query to search for permit holders
* A `setSelected` prop is required which allows the component to return the selected permit holder
* Two new props were added to the `Typeahead` component
* Added spinner to loading state (this loading state is pretty rare, the attached screen recording was taken by deliberately stalling the query)
https://user-images.githubusercontent.com/35577524/141050502-49cbc813-85a5-48a0-8192-3923db91e05f.mov
https://user-images.githubusercontent.com/35577524/141051638-907a7f22-ca97-4ab8-a0d5-84b4fd84d6e7.mov
* Currently testing and demonstrating use of the component in …

[Feature] Hookup permit holder typeahead component

---

components/admin/requests/forms/PaymentDetailsForm.tsx
components/admin/requests/forms/PermitHolderInformationForm.tsx
components/admin/requests/forms/ReasonForReplacementForm.tsx
pages/requests/create-replacement.tsx

[New Replacement Request Page Forms and Cards Frontend](https://www.notion.so/uwblueprintexecs/ac7b1f636a214a0cbf45f6b76f899b54?v=5414ee5fc5974f149921e192d6eb29b8&p=cf49d350118844e999cdfb7c2031650e)
* Created new `create-replacement` page under `pages/requests/create-replacement.tsx`
* Added temporary text input field to act as the Typeahead component
* Added `PermitHolderInformationForm`, `ReasonForReplacementForm`, and `PaymentDetailsForm` components with state variables and state setters
* Built footer component, sticks to bottom of page when scrolling
* No integrated Typeahead component yet
* No functionality with buttons, user ID links, etc.

[Feature] Build Replacement Request Frontend

---

pages/admin/index.tsx
pages/admin/request/create-replacement.tsx

N/A (hotfix)
* Replacement page was under wrong route. Moved from `/requests/create-replacement` to `/admin/request/create-replacement`
* Add authorization check to create replacement page using `getServerSideProps`
* Link to create replacement and create renewal requests pages from requests table

[Hotfix] Move create replacement page to under /admin and add authorization check

---

lib/applications/resolvers.ts

[Format CSV date fields](https://www.notion.so/uwblueprintexecs/Format-CSV-date-fields-1af6ff95d16f43f9a01e68e5ef9fd29c)
* Wrapped date of birth field with `formatDate` util function.
* Changed application date to use PST timezone (should test/confirm this at some point becuase I'm not confident if the conversion is right, @OustanDing mentioned to do separately later on)
CSV with old format:
Applicant DoB,Application Date
Sat Oct 09 2021 20:00:00 GMT-0400 (Eastern Daylight Time),Sat Oct 09 2021 23:20:02 GMT-0400 (Eastern Daylight Time)
CSV with new format:
Applicant DoB,Application Date
10/10/2021,"Oct 09, 2021, 08:20 PM"

[Fix] Format CSV date fields

---

components/admin/requests/SelectedPermitHolderCard.tsx
pages/admin/request/create-renewal.tsx
pages/admin/request/create-replacement.tsx
tools/pages/admin/requests/types.ts

[Add loading states for new renewals/replacements pages when searching for permit holders](https://www.notion.so/uwblueprintexecs/ac7b1f636a214a0cbf45f6b76f899b54?v=5414ee5fc5974f149921e192d6eb29b8&p=0766454ccb0645b3bd2958cc19720ee7)
* Added Loading State to Personal Information Card 
* Added Loading State to Button using Prop
* Searching Load State seems to already be implemented
* Not if I did this comment: `Add loading states for new renewals/replacements pages when searching for permit holders` as only added to Personal Info Card

[Feature] Added Loading States for Renewal / Replacement Flows

---

pages/verify-identity.tsx

[Replace last 4 digits of phone number field with string field](https://www.notion.so/uwblueprintexecs/Replace-last-4-digits-of-phone-number-field-with-string-field-98ff7ee584864d8fbe7abe1aad1a8afd)
* Changed input type of last 4 digits of phone number field from a `NumberInput` to an `Input`
*

[Bug fix] Replace phone number field with string input field

---

lib/applicants/resolvers.ts
lib/applicants/schema.ts
lib/applications/resolvers.ts
lib/applications/schema.ts
lib/graphql/resolvers.ts
lib/graphql/schema.ts
lib/graphql/types.ts

[Reports - Build CSV generation API for permit holders](https://www.notion.so/uwblueprintexecs/Reports-Build-CSV-generation-API-for-permit-holders-96e83e2175714b4a87e69c7301d1d0af)
- Created a GraphQL query endpoint `generatePermitHoldersReport` that takes in an input object `input` with the following fields (all required):
- `startDate` 
- `endDate` 
- `columns` - array of `PermitHoldersReportColumn` enum values
- Created `PermitHoldersReportColumn` enum in `lib/graphql/schema.ts`  with appropriate enum values
- Used Prisma to query the `applicants` table and filter the records by `createdAt` timestamp of applicants' applications
- Used `csv-writer` to subsequently generate a CSV file
The generated file is saved in the file system for now.
GraphQL Query Results:
Generated CSV (UPDATED): …

[Feature] Build CSV generation API for permit holders

---

pages/renew.tsx

[Ticket](https://www.notion.so/uwblueprintexecs/Mark-doctor-phone-number-field-as-required-f4814e5ecfbd4f95b42748807f145981)
* Set `isRequired` on `FormControl` element for doctor phone number in applicant-facing renewal form

[Fix] Make doctor phone number field in applicant renewal form required

---

yarn.lock

N/A
* Downgraded `prisma` to version `2.28` in #122, resulting in dependency mismatch between `package.json` and `yarn.lock`

[Hotfix] Fix yarn.lock file

---

lib/graphql/types.ts
lib/medical-information/schema.ts
tools/pages/admin/permit-holders/get-permit-holder.ts
tools/pages/admin/requests/queries.ts

N/A
* Boolean fields for `cannot_walk_100m`, `affects_mobility` and `mobility_aid_required` were replaced by a single `patient_eligibility` field in #122 
* Not all instances of these fields were removed - some remained in GraphQL queries and schemas
* Fix these instances to use the new `patientEligibility` field instead
* This bug was causing 40x errors as the API schema was execting the boolean fields for inputs

[Hotfix] Remove deprecated fields from GraphQL queries

---

lib/applicants/resolvers.ts
pages/admin/permit-holders.tsx
tools/admin/permit-holders/permit-holders-table.ts

[Ticket](https://www.notion.so/uwblueprintexecs/Fix-applicants-API-filter-5f59658a83a14a6f9bc907f29de6d205)
* `applicants` endpoint was returning no applicants when an empty filter was specified since when an empty filter was specified, only applicants with at least one permit were selected
* Conditionally built filter based on which filters were specified (expiry date, permit status)
* Also fixes a small bug in the permit holders table - if the most recent permit is `null`, "N/A" will now be rendered in the table cell instead of the entire page breaking
* There is still a small bug that deals with timezones and date filtering, which we will further investigate during the date auditing process

[Fix] Fix applicants endpoint filter

---

components/admin/permit-holders/app-history/Card.tsx
lib/applicants/resolvers.ts
pages/admin/permit-holders.tsx
prisma/dev-seed-utils/permits.ts
prisma/seed.ts
prisma/types.ts
tools/admin/permit-holders/permit-holders-table.ts

N/A
* revert changes to applicants resolver which returned all applicants even if they have never had a permit. By reverting this change, we won't show applicants who have never had a permit in the permit holders table and in other use cases for viewing permit holders.
* Add seeding for permits so there are permit holders for testing
* Minor bug fix in App History Card which made the permit status badge always `ACTIVE`
*

[Fix] Revert applicants endpoint and add permits seeding

---

lib/application-processing/resolvers.ts
lib/applications/resolvers.ts
lib/applications/schema.ts
lib/graphql/types.ts
prisma/schema.sql

[Ticket](https://www.notion.so/uwblueprintexecs/Fix-Create-New-APP-API-eacde7c820684c1ca3c7009738180b5e)
* Add `applicantId` as an optional parameter to `createNewApplication`, which connects the new application to the applicant if specified
* In `completeApplication`, for new applications, the resolver no longer creates a new applicant when the new application already has an applicant
* If the applicant already exists, we update the applicant data (+medical information) and upsert guardian info if provided; if guardian info is not provided, we delete the guardian record
* If the applicant does not exist, we create the permit and utilize Prisma transactions to create the applicant and connect the applicant to the application and permit
*

[Fix] Account for existing permit holder when creating and completing new APP applications

---

lib/graphql/schema.ts
lib/graphql/types.ts
lib/reports/resolvers.ts
lib/utils/format.ts
prisma/schema.prisma
prisma/schema.sql

[Update platform payment methods](https://www.notion.so/uwblueprintexecs/ac7b1f636a214a0cbf45f6b76f899b54?v=5414ee5fc5974f149921e192d6eb29b8&p=ba333538f3c34c56ba2df2555f51347c)
* Remove MONEY_ORDER payment method
* Change display of debit to `Interac - Debit (Office)` in table
* Verify that no conflicts with seeding data
* Currently `populate-db-[timestamp].js` has a switch function that operates on the Money_Order data. Not sure if this is to be removed.

[Improvement] Update payment method types

---

lib/reports/resolvers.ts

[Fix accountant report aggregation](https://www.notion.so/uwblueprintexecs/Fix-accountant-report-aggregation-6749e1a1ec87412abee6be8cd23eff3b)
* The Prisma Aggregation Information was not previously being filtered by date. A small code fix was all that was needed to fix the bug (I believe 🤞). Now Fixed Images Below.
One Application Removed via Date Selector:
No Applications Removed via Date Selector:

[Fix] Fix accountant report aggregation bug

---

pages/api/payment-received.ts

[Fix payment confirmation email not sending in staging](https://www.notion.so/uwblueprintexecs/Fix-payment-confirmation-email-not-sending-in-staging-e3849b0ba9ee4f5c8ee3cab8de60bf09)
* prisma is not defined in the payment received handler and needed to be imported
* [NOT VISIBLE IN THIS PR] `CONFIRMATION_EMAIL_FROM` env variable was also missing from the staging and was added to resolve the issue

[Fix] Fix payment confirmation email not sending in staging

---

components/admin/requests/doctor-information/Card.tsx

* Hotfix that adds address title to personal information card.
* Fixes first design suggestion in #156 by @carelynntsai

[Fix] Added Address Title to Doctor's Information Card

---

components/admin/requests/processing/ReviewInformationStep.tsx
components/admin/requests/processing/UndoReviewRequestModal.tsx

[Add Undo Review Confirmation Request modal](https://www.notion.so/uwblueprintexecs/ac7b1f636a214a0cbf45f6b76f899b54?v=5414ee5fc5974f149921e192d6eb29b8&p=ac3417562c394db095887e4f504b3420)
* Added `UndoReviewRequestModal` to components & hooked up with button:

[Feature] Build Undo Confirmation Modal For Processing Tasks

---

components/admin/permit-holders/permit-holder-information/EditModal.tsx
pages/admin/index.tsx
pages/admin/permit-holders.tsx

[Ticket](https://www.notion.so/uwblueprintexecs/Fix-tables-not-updating-when-navigating-back-02f8c3aa3af04d4c8ee994a5b8655ce4)
* Force refetch of requests/permit holders when navigating to table pages to include updates to individual records
* Implemented temporary fix for permit holders table to skip the cache (unideal, added alert comment)
* Fixed minor bug where there are 2 phone number fields in the edit permit holder information modal of the permit holder page
* N/A

[Fix] Fix request and permit holder tables not updating after edit

---

pages/api/auth/[...nextauth].ts

[Disallow inactive employee login](https://www.notion.so/uwblueprintexecs/Disallow-inactive-employee-login-5adf3b5980fe46e88972063dca9946f0)
* Active field is not a findUnique input so I used to select to grab the active field from the matched record and checked if the employee was active
* Because this operation is in a try catch block, the stored result `employee` is not accessible to the catch block so the conditional check if employee is active as well as the throw error statement is in the try block
*

[Bugfix] Disallow Inactive Employee Login

---

components/admin/permit-holders/table/ConfirmSetInactiveModal.tsx
pages/admin/permit-holders.tsx
tools/admin/permit-holders/permit-holders-table.ts

[Hookup set as inactive modal to setApplicantAsInactive endpoint](https://www.notion.so/uwblueprintexecs/ac7b1f636a214a0cbf45f6b76f899b54?v=5414ee5fc5974f149921e192d6eb29b8&p=776057668aee4f44b28869c5e23b4ec1)
* Hooked up the inactive modal to actually change the status of the applicant via the backend gql mutation
[Working Video](https://www.loom.com/share/8875d24cb09b43ce8478d17c6cab8979)

[Improvement] Set Permit Holder as Inactive Modal API Hookup

---

pages/admin/request/[id].tsx

[Cards Still Editable after Review Request step complete](https://www.notion.so/uwblueprintexecs/Cards-Still-Editable-after-Review-Request-step-complete-921c45f0f2ea496a977c6bd4b7ef91e6)
* Add `editDisabled` condition to all cards
*

[Fix] Disable edit on cards when review request completed

---

lib/applications/resolvers.ts
lib/reports/resolvers.ts

[Prevent API updates to applications if review step is completed](https://www.notion.so/uwblueprintexecs/Prevent-API-updates-to-applications-if-review-step-is-completed-a99759aafc7f4f99994bd9cc1807e17f)
* Queried for `reviewRequestCompleted` and threw error if value is true.
Tested locally and the following error is thrown when trying to update while the review request step is marked as completed:
* All the update resolvers in `lib/applications/resolvers.ts` throw if `reviewRequestCompleted` is true ~~except for `updateApplicationPhysicianAssessment` and `updateApplicationAdditionalInformation`. These resolvers aren't hooked up anywhere on the frontend afaik and don't seem related.~~

[Fix] Prevent API updates to applications if review step is completed

---

components/admin/requests/additional-questions/Card.tsx
components/admin/requests/additional-questions/EditModal.tsx
pages/admin/request/[id].tsx
tools/admin/requests/additional-questions.ts

[Create AdditionalInformation EditModal](https://www.notion.so/uwblueprintexecs/Create-AdditionalInformation-EditModal-f22ad680cd5942ee85311c99a7610e0b)
* Built edit modal
* Added `UPDATE_ADDITIONAL_INFORMATION` mutation 
* Connected edit modal to card and displayed card on the requests page
https://user-images.githubusercontent.com/51224641/166408238-649e5f10-69b2-48d7-b1d7-da4264488c79.mov
* Form validation needs to be added and the edit modal will need to be refactored accordingly (needs to be wrapped in a Formik component). I think this can be addressed in the form validation PR once this is merged in.
* As seen in the demo gif, the additional information form on staging does not conditionally render the other fields in the form. This is addressed in the form validation PR here …

[Feature] Create Additional Information Edit Modal

---

components/Table.tsx
pages/admin/index.tsx
pages/admin/permit-holders.tsx

[Add Loading States for Request & Permit Holder Tables](https://www.notion.so/uwblueprintexecs/ac7b1f636a214a0cbf45f6b76f899b54?v=5414ee5fc5974f149921e192d6eb29b8&p=4c73535599df45d6baaad79829933e80)
* Added Loading Component to Table
* Called Loading component with loading parameter from `useQuery`

[Improvement] Added Loading State Spinners to Request & Permit Holder Tables

---

components/admin/permit-holders/Header.tsx
components/admin/permit-holders/additional-notes/Modal.tsx
lib/applicants/resolvers.ts
lib/applicants/schema.ts
lib/graphql/resolvers.ts
lib/graphql/schema.ts
lib/graphql/types.ts
tools/admin/permit-holders/additional-notes.ts

[Hookup set as inactive modal to setApplicantAsInactive endpoint](https://www.notion.so/uwblueprintexecs/Hookup-set-as-inactive-modal-to-setApplicantAsInactive-endpoint-776057668aee4f44b28869c5e23b4ec1)
* Added `updateApplicantNotes` API to resolvers
* Added API call and hookup from `Additional Notes Modal`

[Improvement] Additional Notes API + Hookup

---

components/admin/requests/processing/ReviewInformationStep.tsx
components/admin/requests/processing/TaskCardUploadStep.tsx
components/admin/requests/processing/TasksCard.tsx

[Loading states for processing tasks card](https://www.notion.so/uwblueprintexecs/Loading-states-for-processing-tasks-card-10c896afd09e478ebb77b2af5c4ab77d)
* Added loading states to mark as complete buttons as well as undo buttons
*

[Improvement] Add Loading States to Processing Task Card

---

pages/renew.tsx

[Ticket](https://www.notion.so/uwblueprintexecs/Prevent-applicants-from-submitting-multiple-renewal-requests-860357cc14be4ec8a9f7643e71b6856c)
* Replace the current loading state of the submit button for external applications with loading state that captures the delay in initializing the Shopify cart and redirecting to the checkout
* Tested with success and error paths (injected placeholder error into resolver)

[Fix] Prevent applicants from submitting multiple renewal requests

---

components/admin/requests/physician-assessment/Card.tsx
components/admin/requests/physician-assessment/EditModal.tsx
components/admin/requests/physician-assessment/Form.tsx
lib/physicians/validation.ts

[Add form validation to Physician’s Assessment Card + Edit Modal](https://www.notion.so/uwblueprintexecs/Add-form-validation-to-Physician-s-Assessment-Card-Edit-Modal-d28a20aa43564fcc82b9755e58444ad9)
* Replaced form fields with the custom Formik field components
* Integrated Formik into `EditModal` to work with the modified form 
* Update Yup validation schema to include the new mobility section fields and to resolve a bug with the date fields
Most of the validation can't be triggered (and thus demoed) since some fields inputs can't be emptied (e.g. radio button can't be unselected). 
https://user-images.githubusercontent.com/51224641/170395051-a2708c4d-5147-498e-9966-018cf9bb4345.mov
*

[Feature] Add form validation to Physician’s Assessment Card + Edit Modal

---

lib/applicants/field-resolvers.ts
lib/applicants/resolvers.ts
lib/applicants/schema.ts
lib/graphql/types.ts

[Add omitGuardianPoa to update APIs for applicants](https://www.notion.so/uwblueprintexecs/Add-omitGuardianPoa-to-update-APIs-for-applicants-2946b513057c4821b4cb27b8613954c8)
* Add omitGuardianPoa boolean field as an input to the updateApplicantGuardianInformation endpoint
* If true, disconnect guardian else follow same logic as before
*

[Improvement] Add omitGuardianPoa to update APIs for applicants

---

components/admin/requests/payment-information/Card.tsx
components/admin/requests/payment-information/EditModal.tsx
components/form/ValidationErrorAlert.tsx
lib/applications/resolvers.ts
lib/applications/schema.ts
lib/applications/validation.ts
lib/graphql/types.ts
tools/admin/requests/payment-information.ts

[Payment Information Backend Validation](https://www.notion.so/uwblueprintexecs/Payment-Information-Backend-Validation-374e1d1d86f94226a23c88d54d7d0e7d)
* Returned response from payment information mutation to the edit modal so that it can display error and not close the modal if there is an error.
* Added an error field to return type from graphql mutation so the form validation error can be returned to the frontend.
Example of how a backend form validation error appears in the edit modal. Note that the error shown was manually triggered.
https://user-images.githubusercontent.com/35577524/170796209-65ad4712-a4b4-4900-b9a4-dea5db01deb4.mov
*

[Feature] Payment form backend validation

---

components/admin/permit-holders/doctor-information/Card.tsx
components/admin/permit-holders/guardian-information/Card.tsx
components/admin/permit-holders/permit-holder-information/Card.tsx
lib/applicants/resolvers.ts
lib/applications/resolvers.ts
pages/admin/permit-holders.tsx

[Ticket](https://www.notion.so/uwblueprintexecs/Add-formatting-with-hyphens-to-phone-number-fields-strip-before-saving-to-DB-d4f25d4de5094fc4be0095671d0c218a)
* Strip phone numbers of all non-numeric characters before writing to DB (backend)
* Format all phone numbers (add hyphens) on frontend
*

[Fix] Add phone number formatting

---

components/admin/Address.tsx
components/admin/requests/guardian-information/Card.tsx
lib/applicants/resolvers.ts
lib/applications/resolvers.ts
lib/graphql/types.ts
lib/physicians/schema.ts
lib/utils/format.ts

[Ticket](https://www.notion.so/uwblueprintexecs/Format-postal-code-presentation-and-strip-before-updating-DB-1d0029ed691c421e9dfd5721c51aec14)
* Renamed a formatting function `formatPostalCode` to `stripPostalCode` (strips whitespace, capitalizes alpha characters)
* Created a new formatting function `formatPostalCode` that capitalizes alpha characters and inserts a space to format postal code. Eg. a1b2c3 => A1B 2C3
* Stripped postal codes prior to writing to DB for all instances in resolvers
* Fixed some postal code formatting inconsistencies on frontend
* Also removed an unused GQL schema

[Fix] Format postal code presentation and strip before writing to DB

---

lib/applications/resolvers.ts
lib/applications/schema.ts
lib/applications/validation.ts
lib/graphql/types.ts
pages/renew.tsx
tools/applicant/renew.ts

[External Renewal Form Backend Validation](https://www.notion.so/uwblueprintexecs/External-Renewal-Form-Backend-Validation-9292ec0427f847a9bad2d61d77096f1b)
* Closely follows the implementation of https://github.com/uwblueprint/richmond-centre-for-disability/pull/204
Backend error:
Example of how the backend form validation error is displayed on frontend (the error was manually triggered):
*

[Feature] External Renewal Form Backend Validation

---

components/Table.tsx
lib/applications/resolvers.ts
pages/admin/index.tsx

[Ticket](https://www.notion.so/uwblueprintexecs/Default-sorting-on-requests-page-is-incorrect-ceb45ef380b64d0fbc03a244691f97a1)
* Add `initialSort` prop to `Table` component
* Set the default sort order for the `applications` API to descending by created at time. This way, when the user does not have any sorting selected for the table, the applications are still displayed in an intuitive order
*

[Fix] Fix incorrect default sorting order for requests table

---

pages/admin/permit-holders.tsx

[Fix default sorting for permit holders table](https://www.notion.so/uwblueprintexecs/Fix-default-sorting-for-permit-holders-table-0ac456fac1ee4fa8ba707511c190db7d)
* Adding new initial sort prop to permit holder table 
*

[Fix] Fix default sorting in permit holder table

---

components/admin/permit-holders/guardian-information/Card.tsx
components/admin/requests/guardian-information/Card.tsx
lib/applicants/resolvers.ts
lib/applications/resolvers.ts
tools/admin/requests/guardian-information.ts

[Ticket](https://www.notion.so/uwblueprintexecs/Guardian-Updates-Permit-Holder-Page-4508f599503d4824af71639c77f8bd0c)
* Hook up "Add guardian" buttons to edit guardian modal
* Fixed a bug where updating guardian in applications wouldn't work (omit logic was swapped)
* Fixed a bug where updating guardian for applicants would sometimes fail (if no guardian existed yet, DB nested update would fail)
* Added POA form display to guardian information card for requests
*

[Improvement] Guardian update improvements

---

components/admin/permit-holders/Header.tsx
components/admin/permit-holders/additional-notes/Modal.tsx
lib/applicants/schema.ts
lib/graphql/types.ts
pages/admin/permit-holder/[id].tsx
tools/admin/permit-holders/view-permit-holder.ts

[Ticket](https://www.notion.so/uwblueprintexecs/Show-notes-in-permit-holder-additional-notes-modal-d551b3a4abb14e32b9b192c04caf0261)
* Add `notes` field to `applicant` GraphQL query for additional notes
* Show currently saved additional notes in the additional notes modal upon opening
*

[Fix] Show notes in permit holder additional notes modal

---

components/Typeahead.tsx
components/admin/requests/create/SelectedPermitHolderCard.tsx
pages/admin/request/create-new.tsx
pages/admin/request/create-renewal.tsx
pages/admin/request/create-replacement.tsx

[Ticket](https://www.notion.so/uwblueprintexecs/Search-permit-holder-card-fixes-8d398dcc153644bb8cd1ec9566272113)
*

[Fix] Search permit holder typeahead fixes

---

components/admin/permit-holders/permit-holder-information/Card.tsx
components/admin/requests/Header.tsx
components/admin/requests/guardian-information/Card.tsx
components/admin/requests/processing/ReviewInformationStep.tsx
lib/application-processing/resolvers.ts
lib/invoices/utils.ts
lib/reports/resolvers.ts
lib/utils/permit-expiry.ts
pages/admin/permit-holders.tsx
pages/admin/request/[id].tsx
tools/admin/permit-holders/permit-holders-table.ts

[Ticket](https://www.notion.so/uwblueprintexecs/Various-fixes-from-RCD-meeting-3650bf1c7d0e4960867d799c8b284f1b)
* Following meeting and feedback from RCD

[Fix] Various bug fixes

---

components/applicant/Layout.tsx
pages/index.tsx

[Ticket](https://www.notion.so/uwblueprintexecs/Prevent-RCD-email-from-line-breaking-cf6b2946c5fb42018173bd19d78a3e7d)
* 
*

[Fix] Prevent RCD email from breaking into two lines

---

components/applicant/Layout.tsx
components/applicant/renewals/TOSModal.tsx
pages/index.tsx
pages/privacy-policy.tsx
pages/terms-and-conditions.tsx

[Ticket](https://www.notion.so/uwblueprintexecs/Create-privacy-policy-and-terms-and-conditions-pages-a039808a23d74699af69bbceb759ca6c)
* Add privacy policy and terms and conditions pages
* Fix spacing issue on landing page
*

[Feature] Build privacy policy and terms and conditions pages

---

lib/graphql/apollo.ts
next.config.js

[Ticket](https://www.notion.so/uwblueprintexecs/Disable-access-to-GQL-playground-on-prod-217d3847229c46b5bab34538834f5819)
* 
*

[Fix] Disable GraphQL playground in production

---

lib/applicants/utils.ts

[Ticket](https://www.notion.so/uwblueprintexecs/Change-most-recent-permit-logic-to-use-expiry-date-a54811dbba814fa7947956132fc36201)
* 
*

[Fix] Get most recent permit by latest expiry date

---

lib/applicants/resolvers.ts

[Ticket](https://www.notion.so/uwblueprintexecs/Audit-production-permits-for-invalid-entries-9bbacafd2fc840b9a1af82b46952cd00)
* 
*

[Fix] Restrict permit expiry filter to only active permits

---

lib/reports/resolvers.ts
tools/admin/reports.ts

[Ticket](https://www.notion.so/uwblueprintexecs/Split-address-into-multiple-fields-in-permit-holders-report-b8f5b1b7db694148a80485307cd2e900)
* Split address and guardian address fields in permit holders report
*

[Improvement] Split address fields in permit holders report

---

lib/applicants/resolvers.ts

[Ticket](https://www.notion.so/uwblueprintexecs/Show-applicants-even-if-they-do-not-have-an-active-permit-feb7ecac86bb4e6887e9502f2b4550b1)
* Fixes a bug where applicants that didn't have active permits would not be shown in the permit holders table
*

[Fix] Show applicants even if they do not have an active permit

---

pages/admin/permit-holders.tsx

[Ticket](https://www.notion.so/uwblueprintexecs/Fix-permit-holders-page-breaking-if-permit-holders-do-not-have-most-recent-permit-14c9fc36c17f46de866b3fe5a60a015c)
* 
*

[Fix] Fix permit holders not rendering if no recent permit

---

components/applicant/renewals/RenewalForm/ContactInformationSection.tsx
components/applicant/renewals/RenewalForm/PersonalAddressSection.tsx
components/applicant/renewals/RenewalForm/index.tsx

[Ticket](https://www.notion.so/uwblueprintexecs/Change-Parking-Pass-in-Q-1-2-to-Parking-Permit-db368e3c470443a6b183ece92ca420af)
* Fix copy in applicant flow so that we use "parking permit" everywhere instead of "parking pass"
*

[Fix] Fix inconsistent applicant flow copy

---

lib/applications/resolvers.ts
tools/admin/requests/create-new.ts

[Ticket](https://www.notion.so/uwblueprintexecs/Create-New-APP-not-working-need-more-info-73ba562e58a14a3ab0636b2191148be4)
* Mobility aids fields were not being included in input objects for Yup validation in GraphQL resolvers. Added the fields
*

[Fix] Fix create new APP flow failing

---

package.json

N/A
* Adding port parameter to start script of application for Heroku deployment
*

[Fix] Add port to Next start script

---

lib/graphql/apollo.ts

[Fix] Disable GQL playground and introspection in production

---

components/admin/permit-holders/permit-holder-information/EditModal.tsx
components/admin/requests/additional-questions/EditModal.tsx
components/admin/requests/doctor-information/EditModal.tsx
components/admin/requests/guardian-information/EditModal.tsx
components/admin/requests/payment-information/EditModal.tsx
components/admin/requests/permit-holder-information/EditModal.tsx
components/admin/requests/physician-assessment/EditModal.tsx
components/admin/requests/reason-for-replacement/EditModal.tsx
components/applicant/renewals/IdentityVerification.tsx
components/applicant/renewals/RenewalForm/AdditionalInformationSection.tsx
components/applicant/renewals/RenewalForm/ContactInformationSection.tsx
components/applicant/renewals/RenewalForm/DoctorInformationSection.tsx
components/applicant/renewals/RenewalForm/DonationSection.tsx
components/applicant/renewals/RenewalForm/PersonalAddressSection.tsx
components/form/CheckboxField.tsx
components/form/CheckboxGroupField.tsx
components/form/DateField.tsx
components/form/NumberField.tsx
components/form/RadioGroupField.tsx
components/form/SelectField.tsx
components/form/TextAreaField.tsx
components/form/TextField.tsx
lib/physicians/validation.ts
pages/admin/login.tsx
pages/admin/request/create-new.tsx
pages/admin/request/create-renewal.tsx
pages/admin/request/create-replacement.tsx

[Ticket](https://www.notion.so/uwblueprintexecs/Show-edit-modal-error-messages-on-load-2978ae59f1c04fb2a714dda4bb4c41f5)
* Run validation on form mount, showing validation error messages without requiring `meta.touched` to be true
* Modify physician MSP number (internal only) to support placeholder MSP number (X#####)
*

[Fix] Show validation error messages on form mount

---

lib/invoices/utils.ts

[Ticket](https://www.notion.so/uwblueprintexecs/Invoice-generation-mailing-address-spacing-20e6cb51b3244a18bbdf1a706cf9168d)
* Increase top space for mailing address, increase line height
*

[Improvement] Adjust spacing of address in invoice

---

tools/admin/permit-holders/app-history.ts
tools/admin/permit-holders/view-permit-holder.ts

[Ticket](https://www.notion.so/uwblueprintexecs/Temporary-Permit-Holder-Past-APPs-show-Permanent-instead-of-Temporary-0a3c77770b764a2593295d4ec8feb3e7)
* Include `permitType` in query for APP history
*

[Fix] Fix APP history permit type badge

---

components/admin/requests/Header.tsx
pages/admin/request/[id].tsx
tools/admin/requests/view-request.ts

[Ticket](https://www.notion.so/uwblueprintexecs/Fix-Replacement-expiry-date-display-99e6d065cf454154913c7a479a9c5a81)
* For in-progress replacement applications (not associated with a permit), use the applicant's most recent permit expiry date as the displayed expiry date of the replacement application
*

[Fix] Fix expiry date for in-progress replacement applications

---

prisma/dev-seed-utils/employees.ts

N/A
Add names and emails of new BSF contributors to the Prisma employee database.
Oustan sent a verification request to your Blueprint email for AWS authorization.
To login:
1. Ensure the app is running on localhost
2. Go to `localhost:3000/admin` and sign in with `firstNamelastName+employee@uwblueprint.org`
3. After receiving the login email, ensure you can see the admin portal

[Chore] Add BSF contributors to employee database

---

components/admin/requests/reason-for-replacement/Card.tsx
lib/reports/resolvers.ts
lib/utils/date.ts
pages/admin/index.tsx

[Ticket](https://www.notion.so/uwblueprintexecs/Some-time-zones-are-still-EST-8984f93c38da4fccab00a9b510cade56)
Add new formatter to display request and report dates in local time zone instead of UTC.
* All formatted dates with an associated time (e.g., requests, reports) were replaced with the local formatter.
* All formatted dates without an associated time (e.g., date of birth) were left untouched.

[Fix] Fix time zone for requests and reports

---

components/admin/permit-holders/Header.tsx

[[6] Add note field for permit holder’s old user ID](https://www.notion.so/uwblueprintexecs/6-Add-note-field-for-permit-holder-s-old-user-ID-d8c455a55edf4d2d8c8a23c5a01bc485?pvs=4)
* 
*

[Feature] Add note field for permit holder’s old user ID

---

components/admin/requests/payment-information/Card.tsx
components/admin/requests/payment-information/Form.tsx
lib/applications/resolvers.ts
lib/applications/schema.ts
lib/applications/validation.ts
lib/graphql/types.ts
lib/utils/validation.ts
tools/admin/requests/create-new.ts
tools/admin/requests/payment-information.ts

[Allow processing fee field to be manually edited](https://www.notion.so/uwblueprintexecs/4-Allow-processing-fee-field-to-be-manually-edited-430ed9c5eef445ef82caf9d43b5aac83)
* Allow admins to configure processing fee when creating all types of applications
* Allow admins to edit processing fee
* To prevent completed applications from being edited, should there be another guard aside from https://github.com/uwblueprint/richmond-centre-for-disability/blob/staging/lib/applications/resolvers.ts#L1646-L1649?

[Feature] Allow processing fee field to be manually edited

---

lib/reports/resolvers.ts

[Ticket](https://www.notion.so/uwblueprintexecs/2-Renewal-Report-in-Excel-format-does-not-show-the-most-recent-expiring-permits-ab5f979d40784ed9b72197b07ea6fc3f)
* Show most recent expiring permit rather than most recent created permit in renewal report
* N/A

[Fix] Change renewal report to most recent expiring permits

---

lib/applications/validation.ts
lib/physicians/validation.ts

Doctor's MSP no longer only accepts numbers to be entered
[Doctor's MSP only accepts numbers to be entered](https://www.notion.so/uwblueprintexecs/5-Doctor-s-MSP-only-accepts-numbers-to-be-entered-bbaa5573070e4bf28349a0d1af7ecfa0?pvs=4)
* 
* Should all characters be allowed? Or only letters and numbers? I have currently implemented it such that anything can be entered.

Allow numbers in MSP

---

lib/application-processing/field-resolvers.ts

seems to fix it!
* The reason some task logs were showing and ome were not is because for most applications the application ID did not match the applicationProcessing ID 
This was not a problem for applicationProcessingInvoiceResolver which always used the prisma.applicationProcessing but was for all the rest. I think this should fix the issue but it might need some further testing to see if anything is broken.
*

Show individual steps of the application process

---

README.md

* Windows needs double slashes on this command to work appropriately. Could you double check that this still works on MacOS?
*

Fix bash command for Windows

---

lib/application-processing/resolvers.ts
tools/hooks/graphql.ts

[Unable to create a new permanent permit for an existing temporary permit user](https://www.notion.so/uwblueprintexecs/3-Unable-to-create-a-new-permanent-permit-for-an-existing-temporary-permit-user-a5904b840ed6437ab050b648305410f0)
[Unable to create a new temporary permit for an existing temporary permit user](https://www.notion.so/uwblueprintexecs/4-Unable-to-create-a-new-temporary-permit-for-an-existing-temporary-permit-user-ee5d44fa75f94672a5b669e3bca762ec)
* Turns out the issue with creating permits for existing users does not have to do with permanent/temporary
* Bug is replicated when user has no guardian attached to existing permit and a new permit is created with no guardian
* Attempts to delete the guardian field when it does not exist
* Made changes to application processing …

[Fix] No guardian on delete

---

lib/applicants/resolvers.ts
lib/applicants/schema.ts
lib/graphql/types.ts
pages/admin/permit-holders.tsx

[Some users cannot be found by name search in Permit Holders...allow option to search by permit ID](https://www.notion.so/uwblueprintexecs/13-Some-users-cannot-be-found-by-name-search-in-Permit-Holders-e-g-Po-Sang-Yeung-and-others-with--69e31a14195744cbb2592daf7c0c680c)
Add additional permit ID filter to to applicant GraphQL query and expose on Permit Holders page
**Testing:**
```
rcd=# select * from permits;
rcd_permit_id |   type    | expiry_date | active | application_id | applicant_id |         created_at         |         updated_at
---------------+-----------+-------------+--------+----------------+--------------+----------------------------+----------------------------
1 | PERMANENT | 2018-01-01  | f      |              2 |            2 | 2023-06-18 04:43:10.592+00 | 2023-06-18 …
```

[Feature] Support search by permit ID on Permit Holders page

---

lib/invoices/utils.ts

[Formatting Invoice](https://www.notion.so/uwblueprintexecs/Formatting-invoice-a1082615428c464a9c159eea96c116a6)
* Changed the pdf address spacing from 1.5 to 1.4
* Not sure if this is what RCD wants, we should double-check

Change pdf address spacing from 1.5 to 1.4

---

components/admin/permit-holders/permit-holder-information/Card.tsx

[[22] No text on permit holders page for users that choose other gender](https://www.notion.so/uwblueprintexecs/22-No-text-on-permit-holders-page-for-users-that-choose-other-gender-ded34556b772482cbf7353fe0891bd89)
* Check to see if `otherGender` has a string value associated, otherwise print `titlecase(gender)`, which should be "Other" if gender is "OTHER"
* Seems like this `otherGender` functionality was never [fully implemented](https://github.com/uwblueprint/richmond-centre-for-disability/blob/eb843737b09b1d1a61f38905fe2b8584c5ba90c7/components/admin/requests/permit-holder-information/Form.tsx#L40)

[Fix] Display other gender field on permit holders page

---

components/admin/requests/Header.tsx
components/admin/requests/delete/ConfirmDeleteRequestModal.tsx
lib/applications/resolvers.ts
lib/applications/schema.ts
lib/graphql/resolvers.ts
lib/graphql/schema.ts
lib/graphql/types.ts
pages/admin/request/[id].tsx
tools/admin/requests/delete-request-modal.ts

[Implement application deletion](https://www.notion.so/19-Implement-applications-Deletion-28701aa8b7964893a10e366d2183f2cf)
* Application/request deletion feature
* Designed to maintain consistency with #310
* Fixed from https://github.com/uwblueprint/richmond-centre-for-disability/pull/312
* Database schema changes will need to be enabled to allow for on delete cascade
```
rcd=# select * from replacement_applications where application_id = 3;
application_id | reason |     lost_timestamp     | lost_location | stolen_police_file_number | stolen_jurisdiction | stolen_police_officer_name |                      event_description                      |         created_at         |         updated_at         
----------------+--------+------------------------+---------------+-------------------- …
```

[Feature] Implement application deletion

---

components/admin/permit-holders/Header.tsx
components/admin/permit-holders/table/ConfirmDeleteApplicantModal.tsx
lib/applicants/resolvers.ts
lib/applicants/schema.ts
lib/graphql/resolvers.ts
lib/graphql/schema.ts
lib/graphql/types.ts
pages/admin/permit-holders.tsx
tools/admin/permit-holders/permit-holders-table.ts

[Implement applicant deletion](https://www.notion.so/uwblueprintexecs/18-Implement-User-Deletion-c9b3169b3443421faecf301e64f19a4b)
Applicant deletion feature (note: applicant is called "Permit Holder" in user-facing text)
* Created `deleteApplicant` GraphQL mutation
* Created confirmation modal in frontend, triggered from menus in permit holder table and permit hold info page
Largely follows conventions used for `setApplicantAsInactive` / `setApplicantAsActive` and `deleteEmployee`.
**Delete from table**
Before deletion:
```
rcd=# select * from applicants where id = 4;
id | first_name | middle_name | last_name | date_of_birth | gender | other_gender |   phone    |          email          | receive_email_updates | address_line_1 | address_line_2 |  city  | province | country | postal_code …
```

[Feature] Implement applicant deletion

---

components/admin/requests/permit-holder-information/Card.tsx

[Cannot save edits to personal info section (name or gender) when processing new requests](https://www.notion.so/uwblueprintexecs/23-Cannot-save-edits-to-personal-info-section-name-or-gender-when-processing-new-requests-00a593131eb5499a8bb2e3fbbafec3bb)
* `otherGender` is set to null when updating permit holder information for new applicants
* Quick fix is to set `otherGender` to an empty string on save
* Once schema can be updated to allow `otherGender` to be null, this quick fix can be removed.

[Fix] Set other gender field on permit holders page

---

components/admin/permit-holders/doctor-information/Card.tsx
lib/applicants/resolvers.ts

[[12] Cannot save edited doctor’s info for permit holder if postal code has spacing](https://www.notion.so/uwblueprintexecs/12-Cannot-save-edited-doctor-s-info-for-permit-holder-if-postal-code-has-spacing-f42f0f75a30c4d64aaaa6f17d617cf38?pvs=4)
* No longer make the change for Physician postal code stripping in the frontend.
* Physician postal codes can have a single space in them like is intended.
*

[Fix] Postal Code Space Issue

---

lib/applicants/resolvers.ts

[[17] Guardian/POA file upload does not save the file](https://www.notion.so/uwblueprintexecs/17-Guardian-POA-file-upload-does-not-save-the-file-3ed5816a6e354e80b677697e16a84b78)
* Update updateApplicantGuardianInformation resolver to save the `poaFormS3ObjectKey` to the database
* POA file can also be added/updated when creating or updating a new application, verified that file upload is working correctly in these cases - the problem was isolated to the permit holders page
* There are some existing issues with file upload, namely that there is no validation logic enforcing unique S3 keys for guardians, this means a file can be overwritten if a file of the same name is uploaded for a different guardian. Chose to go with the quick fix first to resolve the originally reported issue, the …

[Fix] Save poaFormS3ObjectKey when updating guardian information in permit holders page

---

lib/employees/resolvers.ts
lib/employees/schema.ts
lib/graphql/resolvers.ts
lib/graphql/schema.ts
lib/graphql/types.ts

[[18][PROD] Issue adding new admin](https://www.notion.so/uwblueprintexecs/18-PROD-Issue-adding-new-admin-a308710ea97d419f9339d65ea5102d41)
* Create new GraphQL endpoint to set an employee to active state
* Meant only for internal use right now, will not expose on UI
```
rcd=# select * from employees where id = 16;
id | first_name | last_name |               email                |       email_verified       | role  | active |         created_at         |          updated_at
----+------------+-----------+------------------------------------+----------------------------+-------+--------+----------------------------+-------------------------------
16 | Sherry     | Li        | sherryli+employee2@uwblueprint.org | 2023-10-02 07:14:32.818+00 | ADMIN | f      | 2023-10-02 07:07:51.834+00 | …
```

[Feature] Create setEmployeeAsActive GraphQL endpoint

---

lib/invoices/utils.ts

[Add spacing to tax receipt](https://www.notion.so/uwblueprintexecs/Add-spacing-to-tax-receipt-3ed828a803714dabbb0109e16e399ccb)
* Updated the donation receipt to match the provided example
* This ticket is actually not complete and should be updated once database migration is allowed. This is because the example donation receipt and permit receipt that RCD provided are of different sizes (Letter vs A4 respectively) and pdfmake doesn't allow us to have 2 pages in the same that are different sizes https://github.com/bpampuch/pdfmake/issues/325. This is important because as mentioned in https://github.com/uwblueprint/richmond-centre-for-disability/pull/311 we are only able to export one pdf without changing the schema, and so we simply concatenate the donation and permit receipt into one …

[Improvement] Update donation receipt spacing

---

lib/physicians/validation.ts

[Physician certification date](https://www.notion.so/uwblueprintexecs/25-Physician-certification-date-12294a50d9e045b3bb0e9a17dfaa9e9a)
* Changes validation schema for physician certification date to dynamically compute current date with `new Date()` on each validation attempt
* Unable to replicate issue exactly, can only assume this happens in a very rare instance where the request page is left open and not completed

[Fix] Adjust schema to evaluate date at validation time

---

components/admin/requests/reason-for-replacement/Form.tsx
pages/admin/request/create-replacement.tsx

[[24] Make replacement requests clearer](https://www.notion.so/uwblueprintexecs/24-Make-replacement-requests-clearer-f8b6511d86584315beea24380247fab0)
* Renamed the reason of replacement from "others" to "mail lost".
* Set a default permit fee of $0 without any specified payment method.
- [ x ] My PR name is descriptive, is in imperative tense and starts with one of the following: `[Feature]`,`[Improvement]` or `[Fix]`,
- [ x ] I have run the appropriate linter(s)
- [ x ] I have requested a review from the RCD team on GitHub, or specific people who are associated with this ticket

[Fix] Make replacement requests clearer

---

.gitignore

Yarn after version 2.0.0 creates a .yarn directory for caching and metadata. This PR ignores that.

Adding the .yarn folder to gitignored.

---

components/admin/requests/reason-for-replacement/Form.tsx
lib/applicants/validation.ts
lib/applications/resolvers.ts
lib/applications/validation.ts

[[26] Replacement request date](https://www.notion.so/uwblueprintexecs/26-Replacement-request-date-05dd117cf6954da3ad303483bbb16a99)
Contains 2 fixes, please review the commits individually:
* 7a47b9572cfcecd9002a5b0f5e2cf6f665d3afe5: reverts validation schema change from #327 to fix the `Field \"otherGender\" is not defined by type \"CreateReplacementApplicationInput` error seen in staging
* `otherGender` is not part of the GraphQL schema for replacement and renewal requests and thus should be marked optional in the validation
* when marked as nullable with default null, a null `otherGender` field is passed for these types of requests and were getting rejected by the backend
* the reason why `nullable().default(null)` did not seem to work for new requests prior to #327 is because the …

[Fix] Fix replacement request otherGender and lostTimestamp form validations

---

components/admin/requests/guardian-information/PoaFormUploadField.tsx

[POA upload bug](https://www.notion.so/uwblueprintexecs/POA-upload-bug-3b092778a8bd44c2856e639e4c4baeb3)
* Update copy to clarify that only lowercase pdf extension will be accepted
* S3 access policy is applied to case-sensitive resource names
* Rather than risking future edge cases by changing the policy, simply communicate the expectation of lowercase to users

[Improvement] Clarify lowercase extension requirement for POA form upload

---

package.json

N/A
Remove `npx` from start command, suspect this is causing an error on start up in staging

[Fix] Remove npx from start script

---

components/applicant/renewals/IdentityVerification.tsx

[Date of birth helper text](https://www.notion.so/uwblueprintexecs/Date-of-birth-helper-text-7d8a5328ea34443592ba7e0e2985dbfe)
* Edit DOB helper text to avoid confusion for those using the mobile date picker
* Mention that the year can be changed by clicking the year for Android users

[Improvement] Change helper text for date of birth

---

lib/invoices/utils.ts

[Donation receipt date issue in file name](https://www.notion.so/uwblueprintexecs/Donation-receipt-date-issue-in-file-name-4d35d47c13754c0486a4f7429d2d3d7a?pvs=4)
There was an issue with the donation receipt name where it was expected to come in a specified format but the receipt names were consistently off within the date section of the name (`PPD_2024012_31631` instead of `PPD_20240112_31631`). 
From close observation, we can see that the issue is that the month value in the date following the YYYMMDD format is zero-indexed and not zero-padded for single digit values, ie. January is 0 instead of 01. This fix applies one-indexing and zero-padding. 
UPDATE: DD (day of the month) should be formatted to be zero padded as well.

[Fix] Fix formatting of date in donation tax receipt number

---

components/admin/requests/payment-information/Form.tsx

[AMEX Second Payment](https://www.notion.so/uwblueprintexecs/AMEX-Second-Payment-ee9b39e2ad5846b29b8af9a4f14fd508)
* AMEX was not previously shown as on the form as a second payment option, backend logic should already be correctly implemented
1. Add a second payment method to a request.
2. Select AMEX as the option.
3. Approve the request.
The steps are outlined in the video below:
<video src=https://github.com/uwblueprint/richmond-centre-for-disability/assets/77544794/42791b26-90d3-494d-bb37-38d8184d0908>

[Fix] Add AMEX as a second payment option

---

README.md

Updating README.md to improve documentation on running and migrations.

[Misc] Update README.md

---

prisma/dev-seed-utils/employees.ts

Add bowen to employees

---

pages/admin/index.tsx
pages/admin/permit-holders.tsx
prisma/dev-seed-utils/employees.ts

[Some letters in names are cut off for those listed under requests and permit holders (ie. 'g', 'q', 'y').](https://www.notion.so/uwblueprintexecs/RCD-Some-letters-in-names-are-cut-off-for-those-listed-under-requests-and-permit-holders-ie-g--ec59bdf999ae4d6f9cf63305cfe1bad8?pvs=4)
* Set `overflow-y: visible` in table rows to avoid having names with tall letters (g, q, y) being cut-off
* Update the email being used for my "employee" account
* Can be verified by checking the requests/permit holders tables and checking that names with letters g/q/y are no longer cut off (seed data does not include one by default I believe)

[Fix] Fix names being clipped in table cell content

---

pages/admin/index.tsx
pages/admin/reports.tsx

[Move the ability to generate application reports from the Request page to the Reports tab](https://www.notion.so/uwblueprintexecs/aa20981f03614ff5a1b2ee2f78aba4cc?v=63e8bea779664acbb10b1ea094e0fdcc&p=5e4db096e41d482facfae986f611fa22&pm=s)
* Accounting admins will only need to see and access the generate report button so it's moved from the request tab to report tab
* report tab page should have generate report button
* request page should just have create request button

move generate report button to reports tab

---

components/applicant/FAQs.tsx
pages/index.tsx

Use the 2024 links for the permit replacement and application forms
[Update forms on RCD website](https://www.notion.so/uwblueprintexecs/RCD-Update-forms-on-RCD-website-981476e69c8f48b6aea006dc21d4c1fb)

Update permit form links

---

.vscode/settings.json
pages/admin/reports.tsx

[Accountant reports with the same start/end date cannot be redownloaded](https://www.notion.so/uwblueprintexecs/RCD-Accountant-reports-with-the-same-start-end-date-cannot-be-redownloaded-e5f09d8cb99e4f0784e38a187b69ecd0)
S3 URL for the generated file expires after 10 seconds (second argument to `getSignedUrlForS3`). Since the Apollo client caches results of all GraphQL queries by default, repeated downloads with the same start and end dates return the same S3 URL, which would be expired. The solution is to force a network call when generating the accountant report in order to always get a fresh URL.
https://github.com/uwblueprint/richmond-centre-for-disability/blob/a9231a39bcf418bea6ebdb6b7a5498aa354ee098/lib/reports/resolvers.ts#L722
Also added VS Code setting to use workspace version of …

[Fix] Force network call for accountant report download

---

.vscode/settings.json
components/admin/requests/payment-information/Form.tsx
components/admin/requests/reason-for-replacement/Form.tsx
components/applicant/FAQs.tsx
pages/admin/index.tsx
pages/admin/permit-holders.tsx
pages/admin/reports.tsx
pages/index.tsx
prisma/dev-seed-utils/employees.ts

- Add bowen to employees (#367)
- Add Jenny to employees (#368)
- [Fix] Mail Lost Default to Cash (#366)
- [Fix] Fix names being clipped in table cell content (#370)
- move generate report button (#369)
- Update permit form links (#373)
- [Fix] Force network call for accountant report download (#371)

[Release] Version 0.3.4

---

components/admin/requests/Header.tsx
pages/admin/index.tsx

[[RCD] Resuming on the previous page](https://www.notion.so/uwblueprintexecs/RCD-Resuming-on-the-previous-page-9de56dfe2f4d4cbbb0b321d6fa04322f?pvs=4)
* Pass application status in router query to keep track of which tab user originated from
* Return to original tab when user clicks `← All Requests`
* Default when navigating to `/admin` is to show the `Pending` applications
* If the user navigates to a request specifically (i.e. without `?origin=`) and then clicks  `← All Requests`, it will bring them back to the same tab as the application's status
* I couldn't bring the user back to the same tab as the application status in all scenarios due to the `All` tab

[enhancement] Track application status to return to original tab in admin view

---

pages/admin/index.tsx
pages/admin/permit-holders.tsx

[Add page scroll to top of permit holders and requests pages](https://www.notion.so/uwblueprintexecs/RCD-Add-page-scroll-to-top-of-permit-holders-and-requests-pages-64d806a816314c24948385a7f4113bf5?pvs=4)
* Add ability to switch page to the top of requests/permit holders tables
*

[Improvement] Add pagination controls to top of requests/permit holders tables

---

prisma/dev-seed-utils/employees.ts

Add Vihaan to employees.ts

---

components/admin/permit-holders/Header.tsx
pages/admin/permit-holder/[id].tsx
pages/admin/permit-holders.tsx
tools/admin/permit-holders/permit-holders-table.ts

[[RCD] Modify User Deletion Feature](https://www.notion.so/uwblueprintexecs/RCD-Modify-User-Deletion-Feature-827f268f5df346a5864c7e6a9ee39485?pvs=4)
* Before
https://github.com/user-attachments/assets/e5c8cc55-4d9d-4195-91e2-ccfd90763d36
* After
https://github.com/user-attachments/assets/2b40ee8a-dcaf-46ee-8c02-750fd61a9cf6

[Improvement] Remove applicant deletion

---

components/admin/permit-holders/app-history/Card/index.tsx
tools/admin/permit-holders/app-history.ts
tools/admin/permit-holders/view-permit-holder.ts

[Reorder permit listings to show the most recent permit requests at the top](https://www.notion.so/uwblueprintexecs/RCD-Permit-Holders-Reorder-permit-listings-to-show-the-most-recent-permit-requests-at-the-top-of--10810f3fb1dc80d2b8c5cab56f12ca6d?pvs=4)
* Sort past applications by creation timestamp in permit holder page
* Did we want to sort by another dimension (updates? by type?)

[Improvement] Sort permit past applications

---

components/admin/requests/Header.tsx
pages/admin/request/[id].tsx
tools/admin/requests/view-request.ts

[Modify user deletion in requests page](https://www.notion.so/uwblueprintexecs/RCD-Modify-user-deletion-in-requests-page-14a10f3fb1dc80928224fbc5954adae8?pvs=4)
* I removed the option to delete a request that has been completed.

[Improvement] Remove completed request deletion

---

components/Pagination.tsx

[Permit holder and request page scroll enhancement](https://www.notion.so/uwblueprintexecs/RCD-Permit-holder-and-request-page-scroll-enhancement-14a10f3fb1dc80c48b4ec77a5cc94f46?pvs=4)
* Adds a text input field to the Pagination component so a page can be specified by typing
* I chose to do the validation upon keyboard input rather than upon hitting of the enter key. I thought this might be less confusing for the user.
https://github.com/user-attachments/assets/f0da7f1f-9624-4052-ab2d-80e44d2723b1

[Feature] Add editable page numbers

---

prisma/schema.prisma

- this is an extension of #381 
* added the `@updatedAt` attribute to all the updatedAt model fields
* same as #381

[Fix] Added updatedAt to the other model fields

---

tools/admin/reports.ts

Change accountant report csv header order(https://www.notion.so/uwblueprintexecs/Change-accountant-report-csv-header-order-f4dd57e9ad67418698f8bf48e9a22844)
Changed the order of the account report csv to better reflect the needs of the accounting department.
* Some headings had different names compared to the titles mentioned in the email. All names were left in their original form.

[Fix] Fixed Finanical Report Header Order

---

components/admin/requests/doctor-information/DoctorTypeahead.tsx
lib/graphql/resolvers.ts
lib/graphql/schema.ts
lib/graphql/types.ts
lib/physicians/resolvers.ts
lib/physicians/schema.ts
pages/admin/request/create-renewal.tsx
tools/admin/requests/doctor-typeahead.ts

[Ability to search for doctors by their MSP number and auto-fill existing doctors' information into the entry field for requests](https://www.notion.so/uwblueprintexecs/RCD-Ability-to-search-for-doctors-by-their-MSP-number-and-auto-fill-existing-doctors-information-i-10810f3fb1dc800aa34cf7d2e4ae5ad7?pvs=4)
* added a DoctorTypeahead similar to the Applicant Typeahead
* added a physicians query to graphql and the necessary resolver
* updated the types to have Physicians filter and Physicians Result
* updated the create-renewal form with the necessary state variable changes to handle the typeahead selection
The demo is below
https://www.loom.com/share/b94202a735334edeba5883214b68ba0b?sid=aa74046e-a318-4b53-a366-c9f58e4b3720

[Feature] Search by Doctor MSP number for Renewal Application

---

components/Pagination.tsx
components/admin/requests/Header.tsx
pages/admin/index.tsx

[[RCD] Resume on the previous tab after viewing user profile](https://www.notion.so/uwblueprintexecs/RCD-Resume-on-the-previous-tab-after-viewing-user-profile-14a10f3fb1dc80929bbdc2fa219828e2)
* Add ability to continue from previous page after clicking `← All Requests`
* Fix bug with paginations numbers not aligning
*

[Improvement] Track page number to return to original page in admin view
